gtl: gtl::RectPrism< Type > Class Template Reference
gtl::RectPrism< Type > Class Template Reference
Represents a rectangular prism as a collection of 8 3D vertices.
#include <gtl/RectPrism.hpp>
Public Member Functions
RectPrism ()
The default constructor makes a cube.
RectPrism (Vec3< Type > *pts)
Constructs a polyhedron from the provided list of 3D points.
int setVertices (Vec3< Type > *pts)
int getNumFillPoints ()
void prepareFill (double resolution)
int getFillPoint (int index, Vec3< Type > &pt)
Detailed Description
template<typename Type>
class gtl::RectPrism< Type >
Represents a rectangular prism as a collection of 8 3D vertices.
Constructor & Destructor Documentation
template<typename Type> gtl::RectPrism< Type >::RectPrism () [inline]
The default constructor makes a cube.
References gtl::Polyhedron< Type >::m_num_vertices, gtl::Polyhedron< Type >::m_vertices, gtl::Vec3< Type >::setValue(), and gtl::RectPrism< Type >::setVertices().
Referenced by gtl::RectPrism< Type >::RectPrism().
template<typename Type> gtl::RectPrism< Type >::RectPrism (Vec3< Type > * pts) [inline]
Constructs a polyhedron from the provided list of 3D points.
References gtl::Polyhedron< Type >::m_num_vertices, gtl::Polyhedron< Type >::m_vertices, gtl::RectPrism< Type >::RectPrism(), and gtl::RectPrism< Type >::setVertices().
Member Function Documentation
template<typename Type> int gtl::RectPrism< Type >::getFillPoint (int index, Vec3< Type > & pt) [inline]
References gtl::RectPrism< Type >::prepareFill(), and gtl::Vec3< Type >::setValue().
template<typename Type> int gtl::RectPrism< Type >::getNumFillPoints () [inline]
References gtl::RectPrism< Type >::prepareFill().
template<typename Type> void gtl::RectPrism< Type >::prepareFill (double resolution) [inline]
References gtl::Vec3< Type >::cross(), gtl::Ray< Type >::getDistance(), gtl::Ray< Type >::getOrigin(), gtl::Vec3< Type >::length(), gtl::Polyhedron< Type >::m_vertices, and gtl::Ray< Type >::setValue().
Referenced by gtl::RectPrism< Type >::getFillPoint(), and gtl::RectPrism< Type >::getNumFillPoints().
template<typename Type> int gtl::RectPrism< Type >::setVertices (Vec3< Type > * pts) [inline]
References gtl::Polyhedron< Type >::setVertices().
Referenced by gtl::RectPrism< Type >::RectPrism().
The documentation for this class was generated from the following file:
rectprism.hpp