gtl: gtl::Box3< Type > Class Template Reference
gtl::Box3< Type > Class Template Reference
Axis-Aligned 3D Bounding Box Class..This box class is used by many other classes.
#include <geometry/Box3.hpp>
Public Member Functions
Box3 ()
The default constructor makes an empty box.
Box3 (const Vec3< Type > &a_min, const Vec3< Type > &a_max)
Constructs a box with the given corners.
virtual ~Box3 ()
Default destructor does nothing.
void setBounds (const Vec3< Type > &a_min, const Vec3< Type > &a_max)
Reset the boundaries of the box with the given corners.
bool isEmpty () const
Check if this has been marked as an empty box.
void makeEmpty ()
Marks this as an empty box.
const Vec3< Type > & getMin () const
Returns the lower left corner of the box.
const Vec3< Type > & getMax () const
Returns the upper right corner of the box.
Vec3< Type > getSize () const
Returns width, height and depth of box.
Vec3< Type > getCenter () const
Returns the center point of the box.
void extendBy (const Vec3< Type > &a_point)
Extend the boundaries of the box by the given point.
void extendBy (const Box3< Type > &a_box)
Extend the boundaries of the box by the given a_box parameter.
Type getVolume () const
Give the volume of the box (0 for an empty box).
void transform (const Matrix4< Type > &m)
Transforms Box3 by matrix, enlarging Box3 to contain result.
bool intersect (const Vec3< Type > &a_point) const
Check if a_point lies within the boundaries of this box.
bool intersect (const Box3< Type > &a_box) const
Check if the given box lies wholly or partly within the boundaries of this box.
bool intersect (const Ray< Type > &a_ray, Type &tmin, Type &tmax) const
Check if the given ray intersect the box.
bool intersect (const Plane< Type > &a_plane) const
Check if the given plane intersect the box.
Friends
bool operator== (const Box3< Type > &b1, const Box3< Type > &b2)
Check b1 and b2 for equality.
bool operator!= (const Box3< Type > &b1, const Box3< Type > &b2)
Check b1 and b2 for inequality.
Detailed Description
template<typename Type>
class gtl::Box3< Type >
Axis-Aligned 3D Bounding Box Class..
This box class is used by many other classes.
See also:
XfBox3
Constructor & Destructor Documentation
template<typename Type> gtl::Box3< Type >::Box3 () [inline]
The default constructor makes an empty box.
References gtl::Box3< Type >::makeEmpty().
template<typename Type> gtl::Box3< Type >::Box3 (const Vec3< Type > & a_min, const Vec3< Type > & a_max) [inline]
Constructs a box with the given corners.
References gtl::Box3< Type >::setBounds().
template<typename Type> virtual gtl::Box3< Type >::~Box3 () [inline, virtual]
Default destructor does nothing.
Member Function Documentation
template<typename Type> void gtl::Box3< Type >::extendBy (const Box3< Type > & a_box) [inline]
Extend the boundaries of the box by the given a_box parameter.
References gtl::Box3< Type >::extendBy(), gtl::Box3< Type >::getMax(), gtl::Box3< Type >::getMin(), and gtl::Box3< Type >::isEmpty().
template<typename Type> void gtl::Box3< Type >::extendBy (const Vec3< Type > & a_point) [inline]
Extend the boundaries of the box by the given point.
Reimplemented in gtl::XfBox3< Type >.
References gtl::Box3< Type >::isEmpty(), and gtl::Box3< Type >::setBounds().
Referenced by gtl::Box3< Type >::extendBy(), gtl::Sphere< Type >::Sphere(), and gtl::Box3< Type >::transform().
template<typename Type> Vec3<Type> gtl::Box3< Type >::getCenter () const [inline]
Returns the center point of the box.
Reimplemented in gtl::XfBox3< Type >.
Referenced by gtl::Sphere< Type >::circumscribe().
template<typename Type> const Vec3<Type>& gtl::Box3< Type >::getMax () const [inline]
Returns the upper right corner of the box.
See also:
getMin().
Referenced by gtl::Sphere< Type >::circumscribe(), gtl::Box3< Type >::extendBy(), gtl::Sphere< Type >::intersect(), and gtl::Sphere< Type >::Sphere().
template<typename Type> const Vec3<Type>& gtl::Box3< Type >::getMin () const [inline]
Returns the lower left corner of the box.
See also:
getCenter(), getMax().
Referenced by gtl::Box3< Type >::extendBy(), gtl::Sphere< Type >::intersect(), and gtl::Sphere< Type >::Sphere().
template<typename Type> Vec3<Type> gtl::Box3< Type >::getSize () const [inline]
Returns width, height and depth of box.
template<typename Type> Type gtl::Box3< Type >::getVolume () const [inline]
Give the volume of the box (0 for an empty box).
Reimplemented in gtl::XfBox3< Type >.
References gtl::Box3< Type >::isEmpty().
template<typename Type> bool gtl::Box3< Type >::intersect (const Plane< Type > & a_plane) const [inline]
Check if the given plane intersect the box.
References gtl::Plane< Type >::getNormal(), gtl::Box3< Type >::isEmpty(), and gtl::Plane< Type >::isInHalfSpace().
template<typename Type> bool gtl::Box3< Type >::intersect (const Ray< Type > & a_ray, Type & tmin, Type & tmax) const [inline]
Check if the given ray intersect the box.
References gtl::Ray< Type >::getDirection(), gtl::Ray< Type >::getOrigin(), gtl::Box3< Type >::isEmpty(), and gtl::sign().
template<typename Type> bool gtl::Box3< Type >::intersect (const Box3< Type > & a_box) const [inline]
Check if the given box lies wholly or partly within the boundaries of this box.
template<typename Type> bool gtl::Box3< Type >::intersect (const Vec3< Type > & a_point) const [inline]
Check if a_point lies within the boundaries of this box.
template<typename Type> bool gtl::Box3< Type >::isEmpty () const [inline]
Check if this has been marked as an empty box.
See also:
makeEmpty().
Referenced by gtl::XfBox3< Type >::extendBy(), gtl::Box3< Type >::extendBy(), gtl::Box3< Type >::getVolume(), gtl::Box3< Type >::intersect(), gtl::XfBox3< Type >::project(), and gtl::Box3< Type >::transform().
template<typename Type> void gtl::Box3< Type >::makeEmpty () [inline]
Marks this as an empty box.
See also:
isEmpty().
Referenced by gtl::Box3< Type >::Box3().
template<typename Type> void gtl::Box3< Type >::setBounds (const Vec3< Type > & a_min, const Vec3< Type > & a_max) [inline]
Reset the boundaries of the box with the given corners.
Referenced by gtl::Box3< Type >::Box3(), gtl::Box3< Type >::extendBy(), and gtl::Box3< Type >::transform().
template<typename Type> void gtl::Box3< Type >::transform (const Matrix4< Type > & m) [inline]
Transforms Box3 by matrix, enlarging Box3 to contain result.
Reimplemented in gtl::XfBox3< Type >.
References gtl::Box3< Type >::extendBy(), gtl::Box3< Type >::isEmpty(), gtl::Matrix4< Type >::multVecMatrix(), and gtl::Box3< Type >::setBounds().
Referenced by gtl::XfBox3< Type >::project().
Friends And Related Function Documentation
template<typename Type> bool operator!= (const Box3< Type > & b1, const Box3< Type > & b2) [friend]
Check b1 and b2 for inequality.
Reimplemented in gtl::XfBox3< Type >.
template<typename Type> bool operator== (const Box3< Type > & b1, const Box3< Type > & b2) [friend]
Check b1 and b2 for equality.
Reimplemented in gtl::XfBox3< Type >.
The documentation for this class was generated from the following file:
box3.hpp