gtl: gtl::Vec4< Type > Class Template Reference
gtl::Vec4< Type > Class Template Reference
4 dimensional vector.This class is used by many other classes.
#include <geometry/Vec4.hpp>
Public Member Functions
Vec4 ()
The default constructor.The vector will be null.
Vec4 (const Type v[4])
Constructs an instance with initial values from v.
Vec4 (Type a_x, Type a_y, Type a_z, Type a_w)
Constructs an instance with the initial values from a_x, a_y, a_z and a_w.
Vec4 (const Vec4< Type > &a_vec)
Constructs an instance with initial values from a_vec.
virtual ~Vec4 ()
Default destructor does nothing.
Vec4< Type > & setValue (const Type v[4])
Set new x, y, z and w values for the vector. Returns reference to self.
Vec4< Type > & setValue (Type a_x, Type a_y, Type a_z, Type a_w)
Set new x, y, z and w values for the vector. Returns reference to self.
const Type * getValue () const
Returns a pointer to an array containing the coordinates of the vector.
void getValue (Type &x, Type &y, Type &z, Type &w) const
Returns the x,y,z and w coordinates of the vector.
Type dot (const Vec4< Type > &a_vec) const
Calculates and returns the dot product of this vector with a_vec.
Type length () const
Return length of vector.
Type sqrLength () const
Return squared length of vector.
Type normalize ()
Normalize the vector to unit length. Return value is the original length of the vector before normalization.
void negate ()
Negate the vector (i.e. point it in the opposite direction).
Type & x ()
Return modifiable x value.
Type & y ()
Return modifiable y value.
Type & z ()
Return modifiable z value.
Type & w ()
Return modifiable w value.
const Type & x () const
Return x value.
const Type & y () const
Return y value.
const Type & z () const
Return z value.
const Type & w () const
Return w value.
Type & operator[] (int i)
Index operator. Returns modifiable x, y, z or w value.
const Type & operator[] (int i) const
Index operator. Returns x, y, z or w value.
Vec4< Type > & operator*= (const Type d)
Multiply components of vector with value d. Returns reference to self.
Vec4< Type > & operator/= (const Type d)
Divides components of vector with value d. Returns reference to self.
Vec4< Type > & operator*= (const Vec4< Type > &a_vec)
Multiply components of vector with value a_vec.
Vec4< Type > & operator+= (const Vec4< Type > &a_vec)
Adds this vector and vector a_vec. Returns reference to self.
Vec4< Type > & operator-= (const Vec4< Type > &a_vec)
Subtracts vector a_vec from this vector. Returns reference to self.
Vec4< Type > operator- () const
Non-destructive negation operator.
bool equals (const Vec4< Type > &a_vec, const Type a_tolerance=1E-2) const
Check for equality with given tolerance.
Static Public Member Functions
static Vec4< Type > max ()
Largest representable vector.
Friends
Vec4< Type > operator* (const Vec4< Type > &a_vec, const Type d)
Vec4< Type > operator* (const Type d, const Vec4< Type > &a_vec)
Vec4< Type > operator/ (const Vec4< Type > &a_vec, const Type d)
Vec4< Type > operator* (const Vec4< Type > &v1, const Vec4< Type > &v2)
Vec4< Type > operator+ (const Vec4< Type > &v1, const Vec4< Type > &v2)
Vec4< Type > operator- (const Vec4< Type > &v1, const Vec4< Type > &v2)
bool operator== (const Vec4< Type > &v1, const Vec4< Type > &v2)
Check the two given vector for equality.
bool operator!= (const Vec4< Type > &v1, const Vec4< Type > &v2)
Check the two given vector for inequality.
std::ostream & operator<< (std::ostream &os, const Vec4< Type > &vect)
Detailed Description
template<typename Type>
class gtl::Vec4< Type >
4 dimensional vector.
This class is used by many other classes.
See also:
Vec3
Constructor & Destructor Documentation
template<typename Type> gtl::Vec4< Type >::Vec4 () [inline]
The default constructor.The vector will be null.
References gtl::Vec4< Type >::setValue().
template<typename Type> gtl::Vec4< Type >::Vec4 (const Type v[4]) [inline]
Constructs an instance with initial values from v.
References gtl::Vec4< Type >::setValue().
template<typename Type> gtl::Vec4< Type >::Vec4 (Type a_x, Type a_y, Type a_z, Type a_w) [inline]
Constructs an instance with the initial values from a_x, a_y, a_z and a_w.
References gtl::Vec4< Type >::setValue().
template<typename Type> gtl::Vec4< Type >::Vec4 (const Vec4< Type > & a_vec) [inline]
Constructs an instance with initial values from a_vec.
References gtl::Vec4< Type >::setValue().
template<typename Type> virtual gtl::Vec4< Type >::~Vec4 () [inline, virtual]
Default destructor does nothing.
Member Function Documentation
template<typename Type> Type gtl::Vec4< Type >::dot (const Vec4< Type > & a_vec) const [inline]
Calculates and returns the dot product of this vector with a_vec.
template<typename Type> bool gtl::Vec4< Type >::equals (const Vec4< Type > & a_vec, const Type a_tolerance = 1E-2) const [inline]
Check for equality with given tolerance.
References gtl::Vec4< Type >::sqrLength().
template<typename Type> void gtl::Vec4< Type >::getValue (Type & x, Type & y, Type & z, Type & w) const [inline]
Returns the x,y,z and w coordinates of the vector.
template<typename Type> const Type* gtl::Vec4< Type >::getValue () const [inline]
Returns a pointer to an array containing the coordinates of the vector.
template<typename Type> Type gtl::Vec4< Type >::length () const [inline]
Return length of vector.
References gtl::Vec4< Type >::sqrLength().
Referenced by gtl::Vec4< Type >::normalize().
template<typename Type> static Vec4<Type> gtl::Vec4< Type >::max () [inline, static]
Largest representable vector.
template<typename Type> void gtl::Vec4< Type >::negate () [inline]
Negate the vector (i.e. point it in the opposite direction).
References gtl::Vec4< Type >::setValue().
template<typename Type> Type gtl::Vec4< Type >::normalize () [inline]
Normalize the vector to unit length. Return value is the original length of the vector before normalization.
References gtl::Vec4< Type >::length(), and gtl::Vec4< Type >::setValue().
template<typename Type> Vec4<Type>& gtl::Vec4< Type >::operator*= (const Vec4< Type > & a_vec) [inline]
Multiply components of vector with value a_vec.
template<typename Type> Vec4<Type>& gtl::Vec4< Type >::operator*= (const Type d) [inline]
Multiply components of vector with value d. Returns reference to self.
template<typename Type> Vec4<Type>& gtl::Vec4< Type >::operator+= (const Vec4< Type > & a_vec) [inline]
Adds this vector and vector a_vec. Returns reference to self.
template<typename Type> Vec4<Type> gtl::Vec4< Type >::operator- () const [inline]
Non-destructive negation operator.
template<typename Type> Vec4<Type>& gtl::Vec4< Type >::operator-= (const Vec4< Type > & a_vec) [inline]
Subtracts vector a_vec from this vector. Returns reference to self.
template<typename Type> Vec4<Type>& gtl::Vec4< Type >::operator/= (const Type d) [inline]
Divides components of vector with value d. Returns reference to self.
template<typename Type> const Type& gtl::Vec4< Type >::operator[] (int i) const [inline]
Index operator. Returns x, y, z or w value.
template<typename Type> Type& gtl::Vec4< Type >::operator[] (int i) [inline]
Index operator. Returns modifiable x, y, z or w value.
template<typename Type> Vec4<Type>& gtl::Vec4< Type >::setValue (Type a_x, Type a_y, Type a_z, Type a_w) [inline]
Set new x, y, z and w values for the vector. Returns reference to self.
template<typename Type> Vec4<Type>& gtl::Vec4< Type >::setValue (const Type v[4]) [inline]
Set new x, y, z and w values for the vector. Returns reference to self.
Referenced by gtl::Vec4< Type >::negate(), gtl::Vec4< Type >::normalize(), and gtl::Vec4< Type >::Vec4().
template<typename Type> Type gtl::Vec4< Type >::sqrLength () const [inline]
Return squared length of vector.
Referenced by gtl::Vec4< Type >::equals(), and gtl::Vec4< Type >::length().
template<typename Type> const Type& gtl::Vec4< Type >::w () const [inline]
Return w value.
template<typename Type> Type& gtl::Vec4< Type >::w () [inline]
Return modifiable w value.
template<typename Type> const Type& gtl::Vec4< Type >::x () const [inline]
Return x value.
template<typename Type> Type& gtl::Vec4< Type >::x () [inline]
Return modifiable x value.
template<typename Type> const Type& gtl::Vec4< Type >::y () const [inline]
Return y value.
template<typename Type> Type& gtl::Vec4< Type >::y () [inline]
Return modifiable y value.
template<typename Type> const Type& gtl::Vec4< Type >::z () const [inline]
Return z value.
template<typename Type> Type& gtl::Vec4< Type >::z () [inline]
Return modifiable z value.
Friends And Related Function Documentation
template<typename Type> bool operator!= (const Vec4< Type > & v1, const Vec4< Type > & v2) [friend]
Check the two given vector for inequality.
template<typename Type> Vec4<Type> operator* (const Vec4< Type > & v1, const Vec4< Type > & v2) [friend]
template<typename Type> Vec4<Type> operator* (const Type d, const Vec4< Type > & a_vec) [friend]
template<typename Type> Vec4<Type> operator* (const Vec4< Type > & a_vec, const Type d) [friend]
template<typename Type> Vec4<Type> operator+ (const Vec4< Type > & v1, const Vec4< Type > & v2) [friend]
template<typename Type> Vec4<Type> operator- (const Vec4< Type > & v1, const Vec4< Type > & v2) [friend]
template<typename Type> Vec4<Type> operator/ (const Vec4< Type > & a_vec, const Type d) [friend]
template<typename Type> std::ostream& operator<< (std::ostream & os, const Vec4< Type > & vect) [friend]
template<typename Type> bool operator== (const Vec4< Type > & v1, const Vec4< Type > & v2) [friend]
Check the two given vector for equality.
The documentation for this class was generated from the following file:
vec4.hpp