gtl: gtl::XfBox3< Type > Class Template Reference
gtl::XfBox3< Type > Class Template Reference
The XfBox3 class is an object oriented box.This box class is used by many other classes.
#include <geometry/XfBox3.hpp>
Public Member Functions
XfBox3 ()
The default constructor makes an empty box.
XfBox3 (const Vec3< Type > &a_min, const Vec3< Type > &a_max)
Constructs a box with the given corners.
XfBox3 (const Box3< Type > &a_box)
void transform (const Matrix4< Type > &m)
Transforms Box3 by matrix, enlarging Box3 to contain result.
void setTransform (const Matrix4< Type > &m)
const Matrix4< Type > & getTransform () const
const Matrix4< Type > & getInverse () const
Vec3< Type > getCenter () const
Returns the center point of the box.
void extendBy (const Vec3< Type > &pt)
Extend the boundaries of the box by the given point.
void extendBy (const Box3< Type > &bb)
Box3< Type > project () const
Type getVolume () const
Give the volume of the box (0 for an empty box).
Friends
bool operator== (const XfBox3< Type > &b1, const XfBox3< Type > &b2)
Check b1 and b2 for equality.
bool operator!= (const XfBox3< Type > &b1, const XfBox3< Type > &b2)
Check b1 and b2 for inequality.
Detailed Description
template<typename Type>
class gtl::XfBox3< Type >
The XfBox3 class is an object oriented box.
This box class is used by many other classes.
See also:
Box3
Constructor & Destructor Documentation
template<typename Type> gtl::XfBox3< Type >::XfBox3 () [inline]
The default constructor makes an empty box.
template<typename Type> gtl::XfBox3< Type >::XfBox3 (const Vec3< Type > & a_min, const Vec3< Type > & a_max) [inline]
Constructs a box with the given corners.
template<typename Type> gtl::XfBox3< Type >::XfBox3 (const Box3< Type > & a_box) [inline]
Member Function Documentation
template<typename Type> void gtl::XfBox3< Type >::extendBy (const Box3< Type > & bb) [inline]
References gtl::Box3< Type >::isEmpty().
template<typename Type> void gtl::XfBox3< Type >::extendBy (const Vec3< Type > & a_point) [inline]
Extend the boundaries of the box by the given point.
Reimplemented from gtl::Box3< Type >.
template<typename Type> Vec3<Type> gtl::XfBox3< Type >::getCenter () const [inline]
Returns the center point of the box.
Reimplemented from gtl::Box3< Type >.
template<typename Type> const Matrix4<Type>& gtl::XfBox3< Type >::getInverse () const [inline]
template<typename Type> const Matrix4<Type>& gtl::XfBox3< Type >::getTransform () const [inline]
template<typename Type> Type gtl::XfBox3< Type >::getVolume () const [inline]
Give the volume of the box (0 for an empty box).
Reimplemented from gtl::Box3< Type >.
template<typename Type> Box3<Type> gtl::XfBox3< Type >::project () const [inline]
References gtl::Box3< Type >::isEmpty(), and gtl::Box3< Type >::transform().
template<typename Type> void gtl::XfBox3< Type >::setTransform (const Matrix4< Type > & m) [inline]
References gtl::Matrix4< Type >::inverse().
Referenced by gtl::XfBox3< Type >::transform().
template<typename Type> void gtl::XfBox3< Type >::transform (const Matrix4< Type > & m) [inline]
Transforms Box3 by matrix, enlarging Box3 to contain result.
Reimplemented from gtl::Box3< Type >.
References gtl::XfBox3< Type >::setTransform().
Friends And Related Function Documentation
template<typename Type> bool operator!= (const XfBox3< Type > & b1, const XfBox3< Type > & b2) [friend]
Check b1 and b2 for inequality.
Reimplemented from gtl::Box3< Type >.
template<typename Type> bool operator== (const XfBox3< Type > & b1, const XfBox3< Type > & b2) [friend]
Check b1 and b2 for equality.
Reimplemented from gtl::Box3< Type >.
The documentation for this class was generated from the following file:
xfbox3.hpp