gtl: gtl::Curve2< Type > Class Template Reference
gtl::Curve2< Type > Class Template Reference
Represents a 2D curve as a collection of non-continuous 2D points.
#include <gtl/curve2.hpp>
Public Types
enum INTERPOL_TYPES { INTERPOL_LINEAR, INTERPOL_AKIMA, NUM_INTERPOL_TYPES }
Public Member Functions
Curve2 ()
The default constructor makes a line segment with 2 points.
Curve2 (const Vec2< Type > *pts, int num_points)
Constructs a curve from the provided list of 2D points.
void setInterpol (INTERPOL_TYPES type)
virtual ~Curve2 ()
Default destructor frees the internal list of 2D points.
int setPoints (const Vec2< Type > *pts, int num_points)
int setPoints (std::vector< Vec2< Type > > &pts, int num_points)
int getPoint (Type x, Vec2< Type > &result) const
Vec2< Type > & start ()
Returns a reference to the start point of the curve.
Vec2< Type > & end ()
Returns a reference to the end point of the curve.
Detailed Description
template<typename Type>
class gtl::Curve2< Type >
Represents a 2D curve as a collection of non-continuous 2D points.
Member Enumeration Documentation
template<typename Type> enum gtl::Curve2::INTERPOL_TYPES
Enumerator:
INTERPOL_LINEAR
INTERPOL_AKIMA
NUM_INTERPOL_TYPES
Constructor & Destructor Documentation
template<typename Type> gtl::Curve2< Type >::Curve2 () [inline]
The default constructor makes a line segment with 2 points.
References gtl::Curve2< Type >::INTERPOL_LINEAR, gtl::Curve2< Type >::setInterpol(), gtl::Curve2< Type >::setPoints(), gtl::Vec2< Type >::x(), and gtl::Vec2< Type >::y().
Referenced by gtl::Curve2< Type >::Curve2().
template<typename Type> gtl::Curve2< Type >::Curve2 (const Vec2< Type > * pts, int num_points) [inline]
Constructs a curve from the provided list of 2D points.
References gtl::Curve2< Type >::Curve2(), gtl::Curve2< Type >::INTERPOL_LINEAR, gtl::Curve2< Type >::setInterpol(), and gtl::Curve2< Type >::setPoints().
template<typename Type> virtual gtl::Curve2< Type >::~Curve2 () [inline, virtual]
Default destructor frees the internal list of 2D points.
Member Function Documentation
template<typename Type> Vec2<Type>& gtl::Curve2< Type >::end () [inline]
Returns a reference to the end point of the curve.
References gtl::Vec2< Type >::x().
template<typename Type> int gtl::Curve2< Type >::getPoint (Type x, Vec2< Type > & result) const [inline]
Returns the point along the curve at position x along the x axis. Returns 0 on success, -1 on error.
References gtl::Curve2< Type >::INTERPOL_AKIMA, gtl::Curve2< Type >::INTERPOL_LINEAR, gtl::Vec2< Type >::x(), and gtl::Vec2< Type >::y().
template<typename Type> void gtl::Curve2< Type >::setInterpol (INTERPOL_TYPES type) [inline]
Performs an interpolation of the specified type (see INTERPOL_TYPES) on the current points for this curve, for the specified resolution.
References gtl::Curve2< Type >::INTERPOL_AKIMA, and gtl::Curve2< Type >::INTERPOL_LINEAR.
Referenced by gtl::Curve2< Type >::Curve2(), and gtl::Curve2< Type >::setPoints().
template<typename Type> int gtl::Curve2< Type >::setPoints (std::vector< Vec2< Type > > & pts, int num_points) [inline]
Reset the initial points describing the curves (pre-interpolation) This one is for point vectors.
References gtl::Curve2< Type >::setInterpol().
template<typename Type> int gtl::Curve2< Type >::setPoints (const Vec2< Type > * pts, int num_points) [inline]
Reset the initial points describing the curves (pre-interpolation) This one is for point arrays.
References gtl::Curve2< Type >::setInterpol().
Referenced by gtl::Curve2< Type >::Curve2().
template<typename Type> Vec2<Type>& gtl::Curve2< Type >::start () [inline]
Returns a reference to the start point of the curve.
References gtl::Vec2< Type >::x().
The documentation for this class was generated from the following file:
curve2.hpp