gtl: gtl::Complex< Type > Class Template Reference
gtl::Complex< Type > Class Template Reference
Represents a complex number.
#include <geometry/Complex.hpp>
Public Member Functions
Complex (Type real, Type imaginary)
Constructs an instance using given real and imaginary values.
Complex (const Complex< Type > &c)
Constructs an instance using values from a given complex instance.
virtual ~Complex ()
Default destructor does nothing.
Complex< Type > & setValue (Type real, Type imaginary)
Set new real and imaginary values for the complex. Returns reference to self.
const Type & getReal () const
Gets the real value of the complex number.
void setReal (Type real)
Sets the real value of the complex number.
const Type & getImaginary () const
Gets the imaginary value of the complex number.
void setImaginary (Type imaginary)
Sets the imaginary value of the complex number.
void negate ()
Negates the complex number.
bool equals (const Complex< Type > &a_complex, const Type a_tolerance=1E-2) const
Check for equality with given tolerance.
Type modulus () const
Gets the modulus of the complex number.
Type sqrModulus () const
Gets the squared modulus of the complex number.
Complex< Type > getConjugate () const
Returns the complex conjugate.
void normalize ()
Normalize the complex number.
Complex< Type > operator- () const
Non-destructive negation operator.
Complex< Type > & operator*= (const Complex< Type > &c)
Complex< Type > & operator*= (const Type &d)
Complex< Type > & operator/= (const Complex< Type > &c)
Complex< Type > & operator/= (const Type &d)
Complex< Type > & operator+= (const Complex< Type > &c)
Complex< Type > & operator+= (const Type &d)
Complex< Type > & operator-= (const Complex< Type > &c)
Complex< Type > & operator-= (const Type &d)
Friends
bool operator== (const Complex< Type > &c1, const Complex< Type > &c2)
Check the two given complex for equality.
bool operator!= (const Complex< Type > &c1, const Complex< Type > &c2)
Check the two given complex for inequality.
Complex< Type > operator* (const Complex< Type > &c1, const Complex< Type > &c2)
Complex< Type > operator* (const Complex< Type > &c, const Type d)
Complex< Type > operator* (const Type d, const Complex< Type > &c)
Complex< Type > operator/ (const Complex< Type > &c, const Type d)
Complex< Type > operator/ (const Complex< Type > &c1, const Complex< Type > &c2)
Complex< Type > operator+ (const Complex< Type > &c1, const Complex< Type > &c2)
Complex< Type > operator+ (const Complex< Type > &c, const Type d)
Complex< Type > operator+ (const Type d, const Complex< Type > &c)
Complex< Type > operator- (const Complex< Type > &c1, const Complex< Type > &c2)
Complex< Type > operator- (const Complex< Type > &c, const Type d)
Complex< Type > operator- (const Type d, const Complex< Type > &c)
Detailed Description
template<typename Type>
class gtl::Complex< Type >
Represents a complex number.
Constructor & Destructor Documentation
template<typename Type> gtl::Complex< Type >::Complex (Type real, Type imaginary) [inline]
Constructs an instance using given real and imaginary values.
References gtl::Complex< Type >::setValue().
template<typename Type> gtl::Complex< Type >::Complex (const Complex< Type > & c) [inline]
Constructs an instance using values from a given complex instance.
References gtl::Complex< Type >::setValue().
template<typename Type> virtual gtl::Complex< Type >::~Complex () [inline, virtual]
Default destructor does nothing.
Member Function Documentation
template<typename Type> bool gtl::Complex< Type >::equals (const Complex< Type > & a_complex, const Type a_tolerance = 1E-2) const [inline]
Check for equality with given tolerance.
template<typename Type> Complex<Type> gtl::Complex< Type >::getConjugate () const [inline]
Returns the complex conjugate.
template<typename Type> const Type& gtl::Complex< Type >::getImaginary () const [inline]
Gets the imaginary value of the complex number.
template<typename Type> const Type& gtl::Complex< Type >::getReal () const [inline]
Gets the real value of the complex number.
template<typename Type> Type gtl::Complex< Type >::modulus () const [inline]
Gets the modulus of the complex number.
References gtl::Complex< Type >::sqrModulus().
Referenced by gtl::Complex< Type >::normalize().
template<typename Type> void gtl::Complex< Type >::negate () [inline]
Negates the complex number.
References gtl::Complex< Type >::setValue().
template<typename Type> void gtl::Complex< Type >::normalize () [inline]
Normalize the complex number.
References gtl::Complex< Type >::modulus().
template<typename Type> Complex<Type>& gtl::Complex< Type >::operator*= (const Type & d) [inline]
template<typename Type> Complex<Type>& gtl::Complex< Type >::operator*= (const Complex< Type > & c) [inline]
template<typename Type> Complex<Type>& gtl::Complex< Type >::operator+= (const Type & d) [inline]
template<typename Type> Complex<Type>& gtl::Complex< Type >::operator+= (const Complex< Type > & c) [inline]
template<typename Type> Complex<Type> gtl::Complex< Type >::operator- () const [inline]
Non-destructive negation operator.
template<typename Type> Complex<Type>& gtl::Complex< Type >::operator-= (const Type & d) [inline]
template<typename Type> Complex<Type>& gtl::Complex< Type >::operator-= (const Complex< Type > & c) [inline]
template<typename Type> Complex<Type>& gtl::Complex< Type >::operator/= (const Type & d) [inline]
template<typename Type> Complex<Type>& gtl::Complex< Type >::operator/= (const Complex< Type > & c) [inline]
References gtl::Complex< Type >::sqrModulus().
template<typename Type> void gtl::Complex< Type >::setImaginary (Type imaginary) [inline]
Sets the imaginary value of the complex number.
template<typename Type> void gtl::Complex< Type >::setReal (Type real) [inline]
Sets the real value of the complex number.
template<typename Type> Complex<Type>& gtl::Complex< Type >::setValue (Type real, Type imaginary) [inline]
Set new real and imaginary values for the complex. Returns reference to self.
Referenced by gtl::Complex< Type >::Complex(), and gtl::Complex< Type >::negate().
template<typename Type> Type gtl::Complex< Type >::sqrModulus () const [inline]
Gets the squared modulus of the complex number.
Referenced by gtl::Complex< Type >::modulus(), and gtl::Complex< Type >::operator/=().
Friends And Related Function Documentation
template<typename Type> bool operator!= (const Complex< Type > & c1, const Complex< Type > & c2) [friend]
Check the two given complex for inequality.
template<typename Type> Complex<Type> operator* (const Type d, const Complex< Type > & c) [friend]
template<typename Type> Complex<Type> operator* (const Complex< Type > & c, const Type d) [friend]
template<typename Type> Complex<Type> operator* (const Complex< Type > & c1, const Complex< Type > & c2) [friend]
template<typename Type> Complex<Type> operator+ (const Type d, const Complex< Type > & c) [friend]
template<typename Type> Complex<Type> operator+ (const Complex< Type > & c, const Type d) [friend]
template<typename Type> Complex<Type> operator+ (const Complex< Type > & c1, const Complex< Type > & c2) [friend]
template<typename Type> Complex<Type> operator- (const Type d, const Complex< Type > & c) [friend]
template<typename Type> Complex<Type> operator- (const Complex< Type > & c, const Type d) [friend]
template<typename Type> Complex<Type> operator- (const Complex< Type > & c1, const Complex< Type > & c2) [friend]
template<typename Type> Complex<Type> operator/ (const Complex< Type > & c1, const Complex< Type > & c2) [friend]
template<typename Type> Complex<Type> operator/ (const Complex< Type > & c, const Type d) [friend]
template<typename Type> bool operator== (const Complex< Type > & c1, const Complex< Type > & c2) [friend]
Check the two given complex for equality.
The documentation for this class was generated from the following file:
complex.hpp