gtl: gtl::Box2< Type > Class Template Reference
gtl::Box2< Type > Class Template Reference
Axis-Aligned 2D Bounding Box Class..This box class is used by many other classes.
#include <geometry/Box2.hpp>
Public Member Functions
Box2 ()
The default constructor makes an empty box.
Box2 (const Vec2< Type > &a_min, const Vec2< Type > &a_max)
Constructs a box with the given corners.
virtual ~Box2 ()
Default destructor does nothing.
void setBounds (const Vec2< Type > &a_min, const Vec2< Type > &a_max)
Reset the boundaries of the box with the given corners.
bool isEmpty () const
Check if this has been marked as an empty box.
void makeEmpty ()
Marks this as an empty box.
const Vec2< Type > & getMin () const
Returns the lower left corner of the box.
const Vec2< Type > & getMax () const
Returns the upper right corner of the box.
Vec2< Type > getSize () const
Returns width and height of box.
Vec2< Type > getCenter () const
Returns the center point of the box.
void extendBy (const Vec2< Type > &a_point)
Extend the boundaries of the box by the given point.
void extendBy (const Box2< Type > &a_box)
Extend the boundaries of the box by the given a_box parameter.
Type getSurface () const
Give the surface of the box.
bool intersect (const Vec2< Type > &a_point) const
Check if a_point lies within the boundaries of this box.
bool intersect (const Box2< Type > &a_box) const
Check if the given box lies wholly or partly within the boundaries of this box.
Friends
bool operator== (const Box2< Type > &b1, const Box2< Type > &b2)
Check b1 and b2 for equality.
bool operator!= (const Box2< Type > &b1, const Box2< Type > &b2)
Check b1 and b2 for inequality.
Detailed Description
template<typename Type>
class gtl::Box2< Type >
Axis-Aligned 2D Bounding Box Class..
This box class is used by many other classes.
See also:
Box3
Constructor & Destructor Documentation
template<typename Type> gtl::Box2< Type >::Box2 () [inline]
The default constructor makes an empty box.
References gtl::Box2< Type >::makeEmpty().
template<typename Type> gtl::Box2< Type >::Box2 (const Vec2< Type > & a_min, const Vec2< Type > & a_max) [inline]
Constructs a box with the given corners.
References gtl::Box2< Type >::setBounds().
template<typename Type> virtual gtl::Box2< Type >::~Box2 () [inline, virtual]
Default destructor does nothing.
Member Function Documentation
template<typename Type> void gtl::Box2< Type >::extendBy (const Box2< Type > & a_box) [inline]
Extend the boundaries of the box by the given a_box parameter.
References gtl::Box2< Type >::extendBy(), gtl::Box2< Type >::getMax(), gtl::Box2< Type >::getMin(), and gtl::Box2< Type >::isEmpty().
template<typename Type> void gtl::Box2< Type >::extendBy (const Vec2< Type > & a_point) [inline]
Extend the boundaries of the box by the given point.
References gtl::Box2< Type >::isEmpty(), and gtl::Box2< Type >::setBounds().
Referenced by gtl::Box2< Type >::extendBy(), and gtl::Polygon< Type >::getBoundingBox().
template<typename Type> Vec2<Type> gtl::Box2< Type >::getCenter () const [inline]
Returns the center point of the box.
template<typename Type> const Vec2<Type>& gtl::Box2< Type >::getMax () const [inline]
Returns the upper right corner of the box.
See also:
getMin().
Referenced by gtl::Box2< Type >::extendBy().
template<typename Type> const Vec2<Type>& gtl::Box2< Type >::getMin () const [inline]
Returns the lower left corner of the box.
See also:
getCenter(), getMax().
Referenced by gtl::Box2< Type >::extendBy().
template<typename Type> Vec2<Type> gtl::Box2< Type >::getSize () const [inline]
Returns width and height of box.
template<typename Type> Type gtl::Box2< Type >::getSurface () const [inline]
Give the surface of the box.
template<typename Type> bool gtl::Box2< Type >::intersect (const Box2< Type > & a_box) const [inline]
Check if the given box lies wholly or partly within the boundaries of this box.
template<typename Type> bool gtl::Box2< Type >::intersect (const Vec2< Type > & a_point) const [inline]
Check if a_point lies within the boundaries of this box.
template<typename Type> bool gtl::Box2< Type >::isEmpty () const [inline]
Check if this has been marked as an empty box.
See also:
makeEmpty().
Referenced by gtl::Box2< Type >::extendBy().
template<typename Type> void gtl::Box2< Type >::makeEmpty () [inline]
Marks this as an empty box.
See also:
isEmpty().
Referenced by gtl::Box2< Type >::Box2().
template<typename Type> void gtl::Box2< Type >::setBounds (const Vec2< Type > & a_min, const Vec2< Type > & a_max) [inline]
Reset the boundaries of the box with the given corners.
Referenced by gtl::Box2< Type >::Box2(), and gtl::Box2< Type >::extendBy().
Friends And Related Function Documentation
template<typename Type> bool operator!= (const Box2< Type > & b1, const Box2< Type > & b2) [friend]
Check b1 and b2 for inequality.
template<typename Type> bool operator== (const Box2< Type > & b1, const Box2< Type > & b2) [friend]
Check b1 and b2 for equality.
The documentation for this class was generated from the following file:
box2.hpp