gtl: gtl::Plane< Type > Class Template Reference
gtl::Plane< Type > Class Template Reference
Represents an oriented plane in 3D.This box class is used by many other classes.
#include <geometry/Plane.hpp>
Public Member Functions
Plane ()
Default constructor. Does nothing.
Plane (const Vec3< Type > &a_normal, Type a_distance)
Construct a Plane from a normal and a distance from coordinate system origin.
Plane (const Vec3< Type > &a_normal, const Vec3< Type > &a_pt)
Construct a Plane from a normal and a point laying in the plane. normal must not be null.
Plane (const Vec3< Type > &a_pt1, const Vec3< Type > &a_pt2, const Vec3< Type > &a_pt3)
Construct a Plane with three points laying in the plane.
Plane (const std::vector< Vec3< Type > > &points)
Computing the Plane Equation of a Polygon.
virtual ~Plane ()
Default destructor does nothing.
void setNormal (const Vec3< Type > &a_normal)
Set the Plane normal.
const Vec3< Type > & getNormal () const
Return the plane's normal vector.
void setDistance (Type a_distance)
Set the distance from coordinate system origin to the plane..
void setValue (Type a, Type b, Type c, Type w)
Set the plane equation. (ax + by + cz + w = 0).
Type getDistanceFromOrigin () const
Return distance from coordinate system origin to the plane.
Type getDistance (const Vec3< Type > &a_point) const
Return the distance from a_point to plane. Positive distance means the point is in the plane's half space.
bool isInHalfSpace (const Vec3< Type > &a_point) const
Check if the given point lies in the halfspace of the plane which the plane normal vector is pointing.
void transform (const Matrix4< Type > &a_matrix)
Transform the plane by the given matrix.
bool equals (const Plane< Type > &a_plane, const Type a_tolerance=EPS) const
Check for equality with given tolerance.
Vec4< Type > equation () const
Return the plane equation. (ax + by + cz + w = 0).
bool intersect (const Ray< Type > &a_ray, Type &t) const
bool intersect (const Plane< Type > &a_plane, Ray< Type > &a_ray) const
bool intersect (const Plane< Type > &a_plane1, const Plane< Type > &a_plane2, Vec3< Type > &a_pt) const
Friends
bool operator== (const Plane< Type > &p1, const Plane< Type > &p2)
Check the two given planes for equality.
bool operator!= (const Plane< Type > &p1, const Plane< Type > &p2)
Check the two given planes for inequality.
Detailed Description
template<typename Type>
class gtl::Plane< Type >
Represents an oriented plane in 3D.
This box class is used by many other classes.
See also:
Box3
Constructor & Destructor Documentation
template<typename Type> gtl::Plane< Type >::Plane () [inline]
Default constructor. Does nothing.
template<typename Type> gtl::Plane< Type >::Plane (const Vec3< Type > & a_normal, Type a_distance) [inline]
Construct a Plane from a normal and a distance from coordinate system origin.
template<typename Type> gtl::Plane< Type >::Plane (const Vec3< Type > & a_normal, const Vec3< Type > & a_pt) [inline]
Construct a Plane from a normal and a point laying in the plane. normal must not be null.
template<typename Type> gtl::Plane< Type >::Plane (const Vec3< Type > & a_pt1, const Vec3< Type > & a_pt2, const Vec3< Type > & a_pt3) [inline]
Construct a Plane with three points laying in the plane.
template<typename Type> gtl::Plane< Type >::Plane (const std::vector< Vec3< Type > > & points) [inline]
Computing the Plane Equation of a Polygon.
References gtl::Vec3< Type >::dot().
template<typename Type> virtual gtl::Plane< Type >::~Plane () [inline, virtual]
Default destructor does nothing.
Member Function Documentation
template<typename Type> bool gtl::Plane< Type >::equals (const Plane< Type > & a_plane, const Type a_tolerance = EPS) const [inline]
Check for equality with given tolerance.
References gtl::Plane< Type >::getDistance(), and gtl::Plane< Type >::getNormal().
template<typename Type> Vec4<Type> gtl::Plane< Type >::equation () const [inline]
Return the plane equation. (ax + by + cz + w = 0).
template<typename Type> Type gtl::Plane< Type >::getDistance (const Vec3< Type > & a_point) const [inline]
Return the distance from a_point to plane. Positive distance means the point is in the plane's half space.
References gtl::Vec3< Type >::dot().
Referenced by gtl::Plane< Type >::equals().
template<typename Type> Type gtl::Plane< Type >::getDistanceFromOrigin () const [inline]
Return distance from coordinate system origin to the plane.
See also:
setDistance(Type a_distance).
template<typename Type> const Vec3<Type>& gtl::Plane< Type >::getNormal () const [inline]
Return the plane's normal vector.
Referenced by gtl::Plane< Type >::equals(), and gtl::Box3< Type >::intersect().
template<typename Type> bool gtl::Plane< Type >::intersect (const Plane< Type > & a_plane1, const Plane< Type > & a_plane2, Vec3< Type > & a_pt) const [inline]
The intersection of three planes. Return true if there is an intersection. a_pt is the point of intersection.
References EPS, and gtl::Vec3< Type >::sqrLength().
template<typename Type> bool gtl::Plane< Type >::intersect (const Plane< Type > & a_plane, Ray< Type > & a_ray) const [inline]
The intersection of two planes. Return true if there is an intersection. a_ray is the line of intersection.
References gtl::Vec3< Type >::cross(), EPS, gtl::Ray< Type >::setValue(), and gtl::Vec3< Type >::setValue().
template<typename Type> bool gtl::Plane< Type >::intersect (const Ray< Type > & a_ray, Type & t) const [inline]
Ray-plane intersection. Return true if there is an intersection. t is the distance from ray origin to plane.
References gtl::Ray< Type >::getDirection(), and gtl::Ray< Type >::getOrigin().
template<typename Type> bool gtl::Plane< Type >::isInHalfSpace (const Vec3< Type > & a_point) const [inline]
Check if the given point lies in the halfspace of the plane which the plane normal vector is pointing.
References gtl::Vec3< Type >::dot().
Referenced by gtl::Box3< Type >::intersect().
template<typename Type> void gtl::Plane< Type >::setDistance (Type a_distance) [inline]
Set the distance from coordinate system origin to the plane..
template<typename Type> void gtl::Plane< Type >::setNormal (const Vec3< Type > & a_normal) [inline]
Set the Plane normal.
See also:
getNormal().
template<typename Type> void gtl::Plane< Type >::setValue (Type a, Type b, Type c, Type w) [inline]
Set the plane equation. (ax + by + cz + w = 0).
template<typename Type> void gtl::Plane< Type >::transform (const Matrix4< Type > & a_matrix) [inline]
Transform the plane by the given matrix.
References gtl::Vec3< Type >::dot(), gtl::Matrix4< Type >::inverse(), gtl::Matrix4< Type >::multDirMatrix(), and gtl::Matrix4< Type >::multVecMatrix().
Friends And Related Function Documentation
template<typename Type> bool operator!= (const Plane< Type > & p1, const Plane< Type > & p2) [friend]
Check the two given planes for inequality.
template<typename Type> bool operator== (const Plane< Type > & p1, const Plane< Type > & p2) [friend]
Check the two given planes for equality.
The documentation for this class was generated from the following file:
plane.hpp