gtl: gtl::Matrix4< Type > Class Template Reference
gtl::Matrix4< Type > Class Template Reference
Row-major 4x4 matrix class.This class is used by many other classes.
#include <geometry/Matrix4.hpp>
Public Member Functions
Matrix4 ()
The default constructor. The matrix will be identity.
Matrix4 (const Type a11, const Type a12, const Type a13, const Type a14, const Type a21, const Type a22, const Type a23, const Type a24, const Type a31, const Type a32, const Type a33, const Type a34, const Type a41, const Type a42, const Type a43, const Type a44)
Constructs a matrix instance with the given initial elements.
Matrix4 (const Matrix4< Type > &a_matrix)
Constructs a matrix instance with the initial elements from the matrix argument.
virtual ~Matrix4 ()
Default destructor does nothing.
void makeIdentity ()
Set the matrix to be the identity matrix.
bool isIdentity () const
Check if matrix is identity.
Matrix4< Type > & invert ()
Inverse the current matrix.
Matrix4< Type > inverse () const
Return a new matrix which is the inverse matrix of this.
Matrix4< Type > & transpose ()
Transpose the current matrix.
Type det3 (int r1, int r2, int r3, int c1, int c2, int c3) const
Returns the determinant of the 3x3 submatrix specified by the row and column indices.
Type det3 () const
Returns the determinant of the upper left 3x3 submatrix.
Type det4 () const
Returns the determinant of the matrix.
bool equals (const Matrix4< Type > &a_matrix, Type a_tolerance=1E-2) const
Check if the a_matrix matrix is equal to this one, within the given tolerance value.
operator Type * ()
Return pointer to the matrix' 4x4 array.
Type * operator[] (int i)
Returns pointer to the 4 element array representing a matrix row. i should be within [0, 3].
const Type * operator[] (int i) const
Returns pointer to the 4 element array representing a matrix row. i should be within [0, 3].
Matrix4< Type > & operator= (const Matrix4< Type > &m)
Assignment operator. Copies the elements from a_matrix to the matrix.
Matrix4< Type > & operator= (const Quat< Type > &a_quat)
Matrix4< Type > & operator*= (const Matrix4< Type > &a_matrix)
Right-multiply with the a_matrix matrix.
void setRotate (const Quat< Type > &a_quat)
void setScale (const Type s)
Set matrix to be a pure scaling matrix. (no translation or rotation components).
void setScale (const Vec3< Type > &s)
Set matrix to be a pure scaling matrix. (no translation or rotation components).
void setTranslate (const Vec3< Type > &t)
Make this matrix into a pure translation matrix. (no scale or rotation components).
Matrix4< Type > & multRight (const Matrix4< Type > &m)
Let this matrix be right-multiplied by m. Returns reference to self.
Matrix4< Type > & multLeft (const Matrix4< Type > &m)
Let this matrix be left-multiplied by m. Returns reference to self.
void multMatrixVec (const Vec3< Type > &src, Vec3< Type > &dst) const
Multiplies matrix by given column vector, giving vector result.
void multVecMatrix (const Vec3< Type > &src, Vec3< Type > &dst) const
Multiplies given row vector by matrix, giving vector result.
void multDirMatrix (const Vec3< Type > &src, Vec3< Type > &dst) const
Friends
Matrix4< Type > operator* (const Matrix4< Type > &m1, const Matrix4< Type > &m2)
Multiplies matrix m1 with matrix m2 and returns the resultant matrix.
bool operator== (const Matrix4< Type > &m1, const Matrix4< Type > &m2)
bool operator!= (const Matrix4< Type > &m1, const Matrix4< Type > &m2)
std::ostream & operator<< (std::ostream &os, const Matrix4< Type > &mat)
Detailed Description
template<typename Type>
class gtl::Matrix4< Type >
Row-major 4x4 matrix class.
This class is used by many other classes.
See also:
Matrix3
Constructor & Destructor Documentation
template<typename Type> gtl::Matrix4< Type >::Matrix4 () [inline]
The default constructor. The matrix will be identity.
References gtl::Matrix4< Type >::makeIdentity().
template<typename Type> gtl::Matrix4< Type >::Matrix4 (const Type a11, const Type a12, const Type a13, const Type a14, const Type a21, const Type a22, const Type a23, const Type a24, const Type a31, const Type a32, const Type a33, const Type a34, const Type a41, const Type a42, const Type a43, const Type a44) [inline]
Constructs a matrix instance with the given initial elements.
template<typename Type> gtl::Matrix4< Type >::Matrix4 (const Matrix4< Type > & a_matrix) [inline]
Constructs a matrix instance with the initial elements from the matrix argument.
template<typename Type> virtual gtl::Matrix4< Type >::~Matrix4 () [inline, virtual]
Default destructor does nothing.
Member Function Documentation
template<typename Type> Type gtl::Matrix4< Type >::det3 () const [inline]
Returns the determinant of the upper left 3x3 submatrix.
Referenced by gtl::Matrix4< Type >::det4().
template<typename Type> Type gtl::Matrix4< Type >::det3 (int r1, int r2, int r3, int c1, int c2, int c3) const [inline]
Returns the determinant of the 3x3 submatrix specified by the row and column indices.
template<typename Type> Type gtl::Matrix4< Type >::det4 () const [inline]
Returns the determinant of the matrix.
References gtl::Matrix4< Type >::det3().
template<typename Type> bool gtl::Matrix4< Type >::equals (const Matrix4< Type > & a_matrix, Type a_tolerance = 1E-2) const [inline]
Check if the a_matrix matrix is equal to this one, within the given tolerance value.
template<typename Type> Matrix4<Type> gtl::Matrix4< Type >::inverse () const [inline]
Return a new matrix which is the inverse matrix of this.
References gtl::Matrix4< Type >::invert().
Referenced by gtl::XfBox3< Type >::setTransform(), and gtl::Plane< Type >::transform().
template<typename Type> Matrix4<Type>& gtl::Matrix4< Type >::invert () [inline]
Inverse the current matrix.
References gtl::Matrix4< Type >::transpose().
Referenced by gtl::Matrix4< Type >::inverse().
template<typename Type> bool gtl::Matrix4< Type >::isIdentity () const [inline]
Check if matrix is identity.
Referenced by gtl::Matrix4< Type >::multLeft(), and gtl::Matrix4< Type >::multRight().
template<typename Type> void gtl::Matrix4< Type >::makeIdentity () [inline]
Set the matrix to be the identity matrix.
See also:
isIdentity().
Referenced by gtl::Matrix4< Type >::Matrix4(), gtl::Matrix4< Type >::setScale(), and gtl::Matrix4< Type >::setTranslate().
template<typename Type> void gtl::Matrix4< Type >::multDirMatrix (const Vec3< Type > & src, Vec3< Type > & dst) const [inline]
Multiplies given row vector by matrix, giving vector result. src is assumed to be a direction vector, so translation part of matrix is ignored. Note: if you wish to transform surface points and normals by a matrix, call multVecMatrix() for the points and call multDirMatrix() on the inverse transpose of the matrix for the normals.
References gtl::Vec3< Type >::setValue().
Referenced by gtl::Plane< Type >::transform().
template<typename Type> Matrix4<Type>& gtl::Matrix4< Type >::multLeft (const Matrix4< Type > & m) [inline]
Let this matrix be left-multiplied by m. Returns reference to self.
References gtl::Matrix4< Type >::isIdentity().
template<typename Type> void gtl::Matrix4< Type >::multMatrixVec (const Vec3< Type > & src, Vec3< Type > & dst) const [inline]
Multiplies matrix by given column vector, giving vector result.
References gtl::Vec3< Type >::setValue().
template<typename Type> Matrix4<Type>& gtl::Matrix4< Type >::multRight (const Matrix4< Type > & m) [inline]
Let this matrix be right-multiplied by m. Returns reference to self.
References gtl::Matrix4< Type >::isIdentity().
Referenced by gtl::Matrix4< Type >::operator*=().
template<typename Type> void gtl::Matrix4< Type >::multVecMatrix (const Vec3< Type > & src, Vec3< Type > & dst) const [inline]
Multiplies given row vector by matrix, giving vector result.
References gtl::Vec3< Type >::setValue().
Referenced by gtl::Plane< Type >::transform(), and gtl::Box3< Type >::transform().
template<typename Type> gtl::Matrix4< Type >::operator Type * () [inline]
Return pointer to the matrix' 4x4 array.
template<typename Type> Matrix4<Type>& gtl::Matrix4< Type >::operator*= (const Matrix4< Type > & a_matrix) [inline]
Right-multiply with the a_matrix matrix.
See also:
multRight().
References gtl::Matrix4< Type >::multRight().
template<typename Type> Matrix4<Type>& gtl::Matrix4< Type >::operator= (const Quat< Type > & a_quat) [inline]
References gtl::Matrix4< Type >::setRotate().
template<typename Type> Matrix4<Type>& gtl::Matrix4< Type >::operator= (const Matrix4< Type > & m) [inline]
Assignment operator. Copies the elements from a_matrix to the matrix.
template<typename Type> const Type* gtl::Matrix4< Type >::operator[] (int i) const [inline]
Returns pointer to the 4 element array representing a matrix row. i should be within [0, 3].
template<typename Type> Type* gtl::Matrix4< Type >::operator[] (int i) [inline]
Returns pointer to the 4 element array representing a matrix row. i should be within [0, 3].
template<typename Type> void gtl::Matrix4< Type >::setRotate (const Quat< Type > & a_quat) [inline]
References gtl::Quat< Type >::getMatrix().
Referenced by gtl::Matrix4< Type >::operator=().
template<typename Type> void gtl::Matrix4< Type >::setScale (const Vec3< Type > & s) [inline]
Set matrix to be a pure scaling matrix. (no translation or rotation components).
References gtl::Matrix4< Type >::makeIdentity().
template<typename Type> void gtl::Matrix4< Type >::setScale (const Type s) [inline]
Set matrix to be a pure scaling matrix. (no translation or rotation components).
template<typename Type> void gtl::Matrix4< Type >::setTranslate (const Vec3< Type > & t) [inline]
Make this matrix into a pure translation matrix. (no scale or rotation components).
References gtl::Matrix4< Type >::makeIdentity().
template<typename Type> Matrix4<Type>& gtl::Matrix4< Type >::transpose () [inline]
Transpose the current matrix.
Referenced by gtl::Matrix4< Type >::invert().
Friends And Related Function Documentation
template<typename Type> bool operator!= (const Matrix4< Type > & m1, const Matrix4< Type > & m2) [friend]
template<typename Type> Matrix4<Type> operator* (const Matrix4< Type > & m1, const Matrix4< Type > & m2) [friend]
Multiplies matrix m1 with matrix m2 and returns the resultant matrix.
template<typename Type> std::ostream& operator<< (std::ostream & os, const Matrix4< Type > & mat) [friend]
template<typename Type> bool operator== (const Matrix4< Type > & m1, const Matrix4< Type > & m2) [friend]
Compare matrices to see if they are equal. For two matrices to be equal, all their individual elements must be equal.
See also:
equals().
The documentation for this class was generated from the following file:
matrix4.hpp