gtl: gtl Namespace Reference
gtl Namespace Reference
Classes
class Box2
Axis-Aligned 2D Bounding Box Class..This box class is used by many other classes.
class Box3
Axis-Aligned 3D Bounding Box Class..This box class is used by many other classes.
class Circle
2 dimensional circle.This class is used by many other classes.
class Complex
Represents a complex number.
class Matrix3
Row-major 3x3 matrix class.This class is used by many other classes.
class Matrix4
Row-major 4x4 matrix class.This class is used by many other classes.
class Plane
Represents an oriented plane in 3D.This box class is used by many other classes.
class Polygon
polygon.This class is used by many other classes.
class Quat
Object that stores a rotation.All angles are in degree and all rotations are right-handed. The rotation is internally stored as a quaternion. This class is used by many other classes.
class Ray
Represents a directed ray in 3D.This class is used by many other classes.
class Sphere
Represents a sphere in 3D.This class is used by many other classes.
class Vec2
2 dimensional vector.This class is used by many other classes.
class Vec3
3 dimensional vector.This class is used by many other classes.
class Vec4
4 dimensional vector.This class is used by many other classes.
class XfBox3
The XfBox3 class is an object oriented box.This box class is used by many other classes.
Typedefs
typedef Box2< int > Box2i
typedef Box2< float > Box2f
typedef Box2< double > Box2d
typedef Box3< int > Box3i
typedef Box3< float > Box3f
typedef Box3< double > Box3d
typedef Circle< int > Circlei
typedef Circle< float > Circlef
typedef Circle< double > Circled
typedef Complex< int > Complexi
typedef Complex< float > Complexf
typedef Complex< double > Complexd
typedef Matrix3< int > Matrix3i
typedef Matrix3< float > Matrix3f
typedef Matrix3< double > Matrix3d
typedef Matrix4< int > Matrix4i
typedef Matrix4< float > Matrix4f
typedef Matrix4< double > Matrix4d
typedef Plane< int > Planei
typedef Plane< float > Planef
typedef Plane< double > Planed
typedef Polygon< int > Polygoni
typedef Polygon< float > Polygonf
typedef Polygon< double > Polygond
typedef Quat< float > Quatf
typedef Quat< double > Quatd
typedef Ray< int > Rayi
typedef Ray< float > Rayf
typedef Ray< double > Rayd
typedef Sphere< int > Spherei
typedef Sphere< float > Spheref
typedef Sphere< double > Sphered
typedef Vec2< int > Vec2i
typedef Vec2< float > Vec2f
typedef Vec2< double > Vec2d
typedef Vec3< int > Vec3i
typedef Vec3< float > Vec3f
typedef Vec3< double > Vec3d
typedef Vec4< int > Vec4i
typedef Vec4< float > Vec4f
typedef Vec4< double > Vec4d
typedef XfBox3< int > XfBox3i
typedef XfBox3< float > XfBox3f
typedef XfBox3< double > XfBox3d
Functions
template<typename Type >
Type DegToRad (Type a)
Convert a_value from degrees to radians.
template<typename Type >
Type RadToDeg (Type a)
Convert a_value from radians to degrees.
template<typename Type >
const Type & min3 (const Type &a, const Type &b, const Type &c)
template<typename Type >
const Type & max3 (const Type &a, const Type &b, const Type &c)
template<typename Type >
void clamp (const Type &min, Type &value, const Type &max)
template<typename Type >
Type rand (const Type min, const Type max)
template<typename Type >
Type sign (Type a)
template<typename Type >
bool equals (const Type &a, const Type &b, Type eps=std::numeric_limits< Type >::epsilon())
bool isPowerOfTwo (int value)
int nearestPowerOfTwo (int value)
Typedef Documentation
typedef Box2<double> gtl::Box2d
typedef Box2<float> gtl::Box2f
typedef Box2<int> gtl::Box2i
typedef Box3<double> gtl::Box3d
typedef Box3<float> gtl::Box3f
typedef Box3<int> gtl::Box3i
typedef Circle<double> gtl::Circled
typedef Circle<float> gtl::Circlef
typedef Circle<int> gtl::Circlei
typedef Complex<double> gtl::Complexd
typedef Complex<float> gtl::Complexf
typedef Complex<int> gtl::Complexi
typedef Matrix3<double> gtl::Matrix3d
typedef Matrix3<float> gtl::Matrix3f
typedef Matrix3<int> gtl::Matrix3i
typedef Matrix4<double> gtl::Matrix4d
typedef Matrix4<float> gtl::Matrix4f
typedef Matrix4<int> gtl::Matrix4i
typedef Plane<double> gtl::Planed
typedef Plane<float> gtl::Planef
typedef Plane<int> gtl::Planei
typedef Polygon<double> gtl::Polygond
typedef Polygon<float> gtl::Polygonf
typedef Polygon<int> gtl::Polygoni
typedef Quat<double> gtl::Quatd
typedef Quat<float> gtl::Quatf
typedef Ray<double> gtl::Rayd
typedef Ray<float> gtl::Rayf
typedef Ray<int> gtl::Rayi
typedef Sphere<double> gtl::Sphered
typedef Sphere<float> gtl::Spheref
typedef Sphere<int> gtl::Spherei
typedef Vec2<double> gtl::Vec2d
typedef Vec2<float> gtl::Vec2f
typedef Vec2<int> gtl::Vec2i
typedef Vec3<double> gtl::Vec3d
typedef Vec3<float> gtl::Vec3f
typedef Vec3<int> gtl::Vec3i
typedef Vec4<double> gtl::Vec4d
typedef Vec4<float> gtl::Vec4f
typedef Vec4<int> gtl::Vec4i
typedef XfBox3<double> gtl::XfBox3d
typedef XfBox3<float> gtl::XfBox3f
typedef XfBox3<int> gtl::XfBox3i
Function Documentation
template<typename Type > void gtl::clamp (const Type & min, Type & value, const Type & max) [inline]
template<typename Type > Type gtl::DegToRad (Type a) [inline]
Convert a_value from degrees to radians.
Referenced by gtl::Quat< Type >::getValue(), and gtl::Quat< Type >::setValue().
template<typename Type > bool gtl::equals (const Type & a, const Type & b, Type eps = std::numeric_limits<Type>::epsilon()) [inline]
bool gtl::isPowerOfTwo (int value) [inline]
template<typename Type > const Type& gtl::max3 (const Type & a, const Type & b, const Type & c) [inline]
template<typename Type > const Type& gtl::min3 (const Type & a, const Type & b, const Type & c) [inline]
int gtl::nearestPowerOfTwo (int value) [inline]
template<typename Type > Type gtl::RadToDeg (Type a) [inline]
Convert a_value from radians to degrees.
Referenced by gtl::Quat< Type >::getValue().
template<typename Type > Type gtl::rand (const Type min, const Type max) [inline]
template<typename Type > Type gtl::sign (Type a) [inline]
Referenced by gtl::Box3< Type >::intersect().