gtl: gtl::Polyhedron< Type > Class Template Reference
gtl::Polyhedron< Type > Class Template Reference
Represents a Polyhedron as a collection of 3D points.
#include <gtl/Polyhedron.hpp>
Public Member Functions
Polyhedron ()
The default constructor makes a tetrahedron.
Polyhedron (const Vec3< Type > *pts, int num_points)
Constructs a polyhedron from the provided list of 3D points.
virtual ~Polyhedron ()
Default destructor frees the internal list of 3D points.
int getNumVertices ()
Returns the number of vertices declared for this polyhedron.
int setVertices (const Vec3< Type > *pts, int num_points)
Reset the vertices describing the polyhedron (must provide more than 3 vertices).
void getVertex (int vertex_index, Vec3< Type > &vertex)
Get a reference to the specified vertex.
void rotate (Vec3< Type > axis, Vec3< Type > point, double angle)
Perform a rotation of the polyhedron around an arbitrary axis by the specified angle in radians.
Protected Attributes
Vec3< Type > * m_vertices
int m_num_vertices
Detailed Description
template<typename Type>
class gtl::Polyhedron< Type >
Represents a Polyhedron as a collection of 3D points.
Constructor & Destructor Documentation
template<typename Type> gtl::Polyhedron< Type >::Polyhedron () [inline]
The default constructor makes a tetrahedron.
References gtl::Polyhedron< Type >::m_num_vertices, gtl::Polyhedron< Type >::m_vertices, gtl::Vec3< Type >::setValue(), and gtl::Polyhedron< Type >::setVertices().
Referenced by gtl::Polyhedron< Type >::Polyhedron().
template<typename Type> gtl::Polyhedron< Type >::Polyhedron (const Vec3< Type > * pts, int num_points) [inline]
Constructs a polyhedron from the provided list of 3D points.
References gtl::Polyhedron< Type >::m_num_vertices, gtl::Polyhedron< Type >::m_vertices, gtl::Polyhedron< Type >::Polyhedron(), and gtl::Polyhedron< Type >::setVertices().
template<typename Type> virtual gtl::Polyhedron< Type >::~Polyhedron () [inline, virtual]
Default destructor frees the internal list of 3D points.
References gtl::Polyhedron< Type >::m_vertices.
Member Function Documentation
template<typename Type> int gtl::Polyhedron< Type >::getNumVertices () [inline]
Returns the number of vertices declared for this polyhedron.
References gtl::Polyhedron< Type >::m_num_vertices.
template<typename Type> void gtl::Polyhedron< Type >::getVertex (int vertex_index, Vec3< Type > & vertex) [inline]
Get a reference to the specified vertex.
References gtl::Polyhedron< Type >::m_num_vertices, gtl::Polyhedron< Type >::m_vertices, and gtl::Vec3< Type >::setValue().
template<typename Type> void gtl::Polyhedron< Type >::rotate (Vec3< Type > axis, Vec3< Type > point, double angle) [inline]
Perform a rotation of the polyhedron around an arbitrary axis by the specified angle in radians.
References gtl::Polyhedron< Type >::m_num_vertices, gtl::Polyhedron< Type >::m_vertices, gtl::Matrix3< Type >::multMatrixVec(), SQR, gtl::Vec3< Type >::x(), gtl::Vec3< Type >::y(), and gtl::Vec3< Type >::z().
template<typename Type> int gtl::Polyhedron< Type >::setVertices (const Vec3< Type > * pts, int num_points) [inline]
Reset the vertices describing the polyhedron (must provide more than 3 vertices).
References gtl::Polyhedron< Type >::m_num_vertices, gtl::Polyhedron< Type >::m_vertices, and MIN_VERTICES.
Referenced by gtl::Polyhedron< Type >::Polyhedron(), and gtl::RectPrism< Type >::setVertices().
Member Data Documentation
template<typename Type> int gtl::Polyhedron< Type >::m_num_vertices [protected]
Referenced by gtl::Polyhedron< Type >::getNumVertices(), gtl::Polyhedron< Type >::getVertex(), gtl::Polyhedron< Type >::Polyhedron(), gtl::RectPrism< Type >::RectPrism(), gtl::Polyhedron< Type >::rotate(), and gtl::Polyhedron< Type >::setVertices().
template<typename Type> Vec3<Type>* gtl::Polyhedron< Type >::m_vertices [protected]
Referenced by gtl::Polyhedron< Type >::getVertex(), gtl::Polyhedron< Type >::Polyhedron(), gtl::RectPrism< Type >::prepareFill(), gtl::RectPrism< Type >::RectPrism(), gtl::Polyhedron< Type >::rotate(), gtl::Polyhedron< Type >::setVertices(), and gtl::Polyhedron< Type >::~Polyhedron().
The documentation for this class was generated from the following file:
polyhedron.hpp