gtl: gtl::Curve< Type > Class Template Reference
gtl::Curve< Type > Class Template Reference
Represents a 2D curve as a collection of non-continuous 2D points.
#include <gtl/Curve.hpp>
Public Types
enum INTERPOL_TYPES { INTERPOL_LINEAR, INTERPOL_AKIMA, NUM_INTERPOL_TYPES }
Public Member Functions
Curve ()
The default constructor makes a line segment with 2 points.
Curve (const Vec2< Type > *pts, int num_points)
Constructs a curve from the provided list of 2D points.
void set_interpol (INTERPOL_TYPES type)
virtual ~Curve ()
Default destructor frees the internal list of 2D points.
int setPoints (const Vec2< Type > *pts, int num_points)
Reset the initial points describing the curves (pre-interpolation).
int getPoint (Type x, Vec2< Type > &result) const
Vec2< Type > & start ()
Returns a reference to the start point of the curve.
Vec2< Type > & end ()
Returns a reference to the end point of the curve.
Protected Member Functions
void init_linear (const Vec2< Type > *pts, int num_points)
void init_akima (const Vec2< Type > *pts, int num_points)
Type get_linear (Type x_pos) const
Type get_akima (Type x_pos) const
Protected Attributes
INTERPOL_TYPES m_current_interpol
Vec2< Type > * m_points
int m_num_points
double * m_interpol_x
double * m_interpol_y
double * m_interpol_z
double * m_interpol_t
Detailed Description
template<typename Type>
class gtl::Curve< Type >
Represents a 2D curve as a collection of non-continuous 2D points.
Member Enumeration Documentation
template<typename Type> enum gtl::Curve::INTERPOL_TYPES
Enumerator:
INTERPOL_LINEAR
INTERPOL_AKIMA
NUM_INTERPOL_TYPES
Constructor & Destructor Documentation
template<typename Type> gtl::Curve< Type >::Curve () [inline]
The default constructor makes a line segment with 2 points.
References gtl::Curve< Type >::init_linear(), gtl::Curve< Type >::m_interpol_t, gtl::Curve< Type >::m_interpol_x, gtl::Curve< Type >::m_interpol_y, gtl::Curve< Type >::m_interpol_z, gtl::Curve< Type >::m_num_points, gtl::Curve< Type >::m_points, gtl::Curve< Type >::setPoints(), gtl::Vec2< Type >::x(), and gtl::Vec2< Type >::y().
Referenced by gtl::Curve< Type >::Curve().
template<typename Type> gtl::Curve< Type >::Curve (const Vec2< Type > * pts, int num_points) [inline]
Constructs a curve from the provided list of 2D points.
References gtl::Curve< Type >::Curve(), gtl::Curve< Type >::init_linear(), gtl::Curve< Type >::m_interpol_t, gtl::Curve< Type >::m_interpol_x, gtl::Curve< Type >::m_interpol_y, gtl::Curve< Type >::m_interpol_z, gtl::Curve< Type >::m_num_points, gtl::Curve< Type >::m_points, and gtl::Curve< Type >::setPoints().
template<typename Type> virtual gtl::Curve< Type >::~Curve () [inline, virtual]
Default destructor frees the internal list of 2D points.
References gtl::Curve< Type >::m_interpol_t, gtl::Curve< Type >::m_interpol_x, gtl::Curve< Type >::m_interpol_y, gtl::Curve< Type >::m_interpol_z, and gtl::Curve< Type >::m_points.
Member Function Documentation
template<typename Type> Vec2<Type>& gtl::Curve< Type >::end () [inline]
Returns a reference to the end point of the curve.
References gtl::Curve< Type >::m_num_points, gtl::Curve< Type >::m_points, and gtl::Vec2< Type >::x().
template<typename Type> Type gtl::Curve< Type >::get_akima (Type x_pos) const [inline, protected]
References gtl::Curve< Type >::m_interpol_t, gtl::Curve< Type >::m_interpol_x, gtl::Curve< Type >::m_interpol_y, gtl::Curve< Type >::m_interpol_z, and SQR.
Referenced by gtl::Curve< Type >::getPoint().
template<typename Type> Type gtl::Curve< Type >::get_linear (Type x_pos) const [inline, protected]
References gtl::Curve< Type >::m_interpol_x, and gtl::Curve< Type >::m_interpol_y.
Referenced by gtl::Curve< Type >::getPoint().
template<typename Type> int gtl::Curve< Type >::getPoint (Type x, Vec2< Type > & result) const [inline]
Returns the point along the curve at position x along the x axis. Returns 0 on success, -1 on error.
References gtl::Curve< Type >::get_akima(), gtl::Curve< Type >::get_linear(), gtl::Curve< Type >::INTERPOL_AKIMA, gtl::Curve< Type >::INTERPOL_LINEAR, gtl::Curve< Type >::m_current_interpol, gtl::Vec2< Type >::x(), and gtl::Vec2< Type >::y().
template<typename Type> void gtl::Curve< Type >::init_akima (const Vec2< Type > * pts, int num_points) [inline, protected]
References gtl::Curve< Type >::INTERPOL_AKIMA, gtl::Curve< Type >::m_current_interpol, gtl::Curve< Type >::m_interpol_t, gtl::Curve< Type >::m_interpol_x, gtl::Curve< Type >::m_interpol_y, gtl::Curve< Type >::m_interpol_z, gtl::Vec2< Type >::x(), and gtl::Vec2< Type >::y().
Referenced by gtl::Curve< Type >::set_interpol().
template<typename Type> void gtl::Curve< Type >::init_linear (const Vec2< Type > * pts, int num_points) [inline, protected]
References gtl::Curve< Type >::INTERPOL_LINEAR, gtl::Curve< Type >::m_current_interpol, gtl::Curve< Type >::m_interpol_x, gtl::Curve< Type >::m_interpol_y, gtl::Vec2< Type >::x(), and gtl::Vec2< Type >::y().
Referenced by gtl::Curve< Type >::Curve(), and gtl::Curve< Type >::set_interpol().
template<typename Type> void gtl::Curve< Type >::set_interpol (INTERPOL_TYPES type) [inline]
Performs an interpolation of the specified type (see INTERPOL_TYPES) on the current points for this curve, for the specified resolution.
References gtl::Curve< Type >::init_akima(), gtl::Curve< Type >::init_linear(), gtl::Curve< Type >::INTERPOL_AKIMA, gtl::Curve< Type >::INTERPOL_LINEAR, gtl::Curve< Type >::m_num_points, and gtl::Curve< Type >::m_points.
Referenced by gtl::Curve< Type >::setPoints().
template<typename Type> int gtl::Curve< Type >::setPoints (const Vec2< Type > * pts, int num_points) [inline]
Reset the initial points describing the curves (pre-interpolation).
References gtl::Curve< Type >::m_current_interpol, gtl::Curve< Type >::m_num_points, gtl::Curve< Type >::m_points, and gtl::Curve< Type >::set_interpol().
Referenced by gtl::Curve< Type >::Curve().
template<typename Type> Vec2<Type>& gtl::Curve< Type >::start () [inline]
Returns a reference to the start point of the curve.
References gtl::Curve< Type >::m_num_points, gtl::Curve< Type >::m_points, and gtl::Vec2< Type >::x().
Member Data Documentation
template<typename Type> INTERPOL_TYPES gtl::Curve< Type >::m_current_interpol [protected]
Referenced by gtl::Curve< Type >::getPoint(), gtl::Curve< Type >::init_akima(), gtl::Curve< Type >::init_linear(), and gtl::Curve< Type >::setPoints().
template<typename Type> double* gtl::Curve< Type >::m_interpol_t [protected]
Referenced by gtl::Curve< Type >::Curve(), gtl::Curve< Type >::get_akima(), gtl::Curve< Type >::init_akima(), and gtl::Curve< Type >::~Curve().
template<typename Type> double* gtl::Curve< Type >::m_interpol_x [protected]
Referenced by gtl::Curve< Type >::Curve(), gtl::Curve< Type >::get_akima(), gtl::Curve< Type >::get_linear(), gtl::Curve< Type >::init_akima(), gtl::Curve< Type >::init_linear(), and gtl::Curve< Type >::~Curve().
template<typename Type> double* gtl::Curve< Type >::m_interpol_y [protected]
Referenced by gtl::Curve< Type >::Curve(), gtl::Curve< Type >::get_akima(), gtl::Curve< Type >::get_linear(), gtl::Curve< Type >::init_akima(), gtl::Curve< Type >::init_linear(), and gtl::Curve< Type >::~Curve().
template<typename Type> double* gtl::Curve< Type >::m_interpol_z [protected]
Referenced by gtl::Curve< Type >::Curve(), gtl::Curve< Type >::get_akima(), gtl::Curve< Type >::init_akima(), and gtl::Curve< Type >::~Curve().
template<typename Type> int gtl::Curve< Type >::m_num_points [protected]
Referenced by gtl::Curve< Type >::Curve(), gtl::Curve< Type >::end(), gtl::Curve< Type >::set_interpol(), gtl::Curve< Type >::setPoints(), and gtl::Curve< Type >::start().
template<typename Type> Vec2<Type>* gtl::Curve< Type >::m_points [protected]
Referenced by gtl::Curve< Type >::Curve(), gtl::Curve< Type >::end(), gtl::Curve< Type >::set_interpol(), gtl::Curve< Type >::setPoints(), gtl::Curve< Type >::start(), and gtl::Curve< Type >::~Curve().
The documentation for this class was generated from the following file:
curve.hpp