gtl: gtl::Segment2< Type > Class Template Reference
gtl::Segment2< Type > Class Template Reference
Represents a 2D line segment as a special case of a curve that is declared from 2 2D points.
#include <gtl/segment2.hpp>
Public Member Functions
Segment2 ()
The default constructor makes a line segment with 2 points.
Segment2 (Vec2< Type > &start_pt, Vec2< Type > &end_pt)
Constructs a line segment from the 2 provided 2D points.
int setPoints (Vec2< Type > &start_pt, Vec2< Type > &end_pt)
Reset the two points from which the line segment is declared.
Type getDistance (Vec2< Type > point)
Returns the distance from the specified point to the line extended from this line segment.
Type length ()
Returns the length of the line segment.
Static Public Member Functions
static void getEquation (Vec2< Type > &pt1, Vec2< Type > &pt2, Type &m, Type &b)
Returns the equation of a line in the form y = mx + b, given two 2D points.
Protected Attributes
Vec2< Type > m_initial_points [2]
Detailed Description
template<typename Type>
class gtl::Segment2< Type >
Represents a 2D line segment as a special case of a curve that is declared from 2 2D points.
Constructor & Destructor Documentation
template<typename Type> gtl::Segment2< Type >::Segment2 () [inline]
The default constructor makes a line segment with 2 points.
References gtl::Segment2< Type >::m_initial_points, gtl::Vec2< Type >::x(), and gtl::Vec2< Type >::y().
Referenced by gtl::Segment2< Type >::Segment2().
template<typename Type> gtl::Segment2< Type >::Segment2 (Vec2< Type > & start_pt, Vec2< Type > & end_pt) [inline]
Constructs a line segment from the 2 provided 2D points.
References gtl::Segment2< Type >::Segment2(), and gtl::Segment2< Type >::setPoints().
Member Function Documentation
template<typename Type> Type gtl::Segment2< Type >::getDistance (Vec2< Type > point) [inline]
Returns the distance from the specified point to the line extended from this line segment.
References gtl::Segment2< Type >::getEquation(), gtl::Segment2< Type >::m_initial_points, SQR, gtl::Vec2< Type >::x(), and gtl::Vec2< Type >::y().
template<typename Type> static void gtl::Segment2< Type >::getEquation (Vec2< Type > & pt1, Vec2< Type > & pt2, Type & m, Type & b) [inline, static]
Returns the equation of a line in the form y = mx + b, given two 2D points.
References gtl::Vec2< Type >::x(), and gtl::Vec2< Type >::y().
Referenced by gtl::Segment2< Type >::getDistance().
template<typename Type> Type gtl::Segment2< Type >::length () [inline]
Returns the length of the line segment.
References gtl::Segment2< Type >::m_initial_points.
template<typename Type> int gtl::Segment2< Type >::setPoints (Vec2< Type > & start_pt, Vec2< Type > & end_pt) [inline]
Reset the two points from which the line segment is declared.
References gtl::Segment2< Type >::m_initial_points.
Referenced by gtl::Segment2< Type >::Segment2().
Member Data Documentation
template<typename Type> Vec2<Type> gtl::Segment2< Type >::m_initial_points[2] [protected]
Referenced by gtl::Segment2< Type >::getDistance(), gtl::Segment2< Type >::length(), gtl::Segment2< Type >::Segment2(), and gtl::Segment2< Type >::setPoints().
The documentation for this class was generated from the following file:
segment2.hpp