gtl: gtl::Ray< Type > Class Template Reference
gtl::Ray< Type > Class Template Reference
Represents a directed ray in 3D.This class is used by many other classes.
#include <geometry/Ray.hpp>
Public Member Functions
Ray (const Ray< Type > &a_ray)
Constructs an instance with initial values from a_ray.
Ray (const Vec3< Type > &a_origin, const Vec3< Type > &a_direction, bool normalize=true)
Create a ray from a_origin with the direction a_direction. If normalize is true, a_direction will be normalized.
virtual ~Ray ()
Default destructor does nothing.
void setValue (const Vec3< Type > &a_origin, const Vec3< Type > &a_direction, bool normalize=true)
Set position and direction of the ray. If normalize is true, a_direction will be normalized.
const Vec3< Type > & getOrigin () const
Return the ray origin.
const Vec3< Type > & getDirection () const
Return the ray normalized direction.
Vec3< Type > getValue (Type t) const
Get point on ray at t.
Type getDistance (const Vec3< Type > &pt) const
Distance point line.
Type getSqrDistance (const Vec3< Type > &pt) const
Squared distance point line.
Ray< Type > reflect (const Vec3< Type > &newOrigin, const Vec3< Type > &normal) const
Reflects about normal and return a new ray with origin at newOrigin.
Vec3< Type > project (const Vec3< Type > &pt) const
Project the given point on the ray.
bool intersect (const Vec3< Type > &vert0, const Vec3< Type > &vert1, const Vec3< Type > &vert2, Vec3< Type > &a_tuv) const
bool intersect (const Ray< Type > &a_ray, Type &mua, Type &mub) const
Friends
bool operator== (const Ray< Type > &r1, const Ray< Type > &r2)
Check the two given ray for equality.
bool operator!= (const Ray< Type > &r1, const Ray< Type > &r2)
Check the two given ray for inequality.
Detailed Description
template<typename Type>
class gtl::Ray< Type >
Represents a directed ray in 3D.
This class is used by many other classes.
See also:
Vec3
Constructor & Destructor Documentation
template<typename Type> gtl::Ray< Type >::Ray (const Ray< Type > & a_ray) [inline]
Constructs an instance with initial values from a_ray.
template<typename Type> gtl::Ray< Type >::Ray (const Vec3< Type > & a_origin, const Vec3< Type > & a_direction, bool normalize = true) [inline]
Create a ray from a_origin with the direction a_direction. If normalize is true, a_direction will be normalized.
References gtl::Ray< Type >::setValue().
template<typename Type> virtual gtl::Ray< Type >::~Ray () [inline, virtual]
Default destructor does nothing.
Member Function Documentation
template<typename Type> const Vec3<Type>& gtl::Ray< Type >::getDirection () const [inline]
Return the ray normalized direction.
Referenced by gtl::Sphere< Type >::intersect(), gtl::Plane< Type >::intersect(), and gtl::Box3< Type >::intersect().
template<typename Type> Type gtl::Ray< Type >::getDistance (const Vec3< Type > & pt) const [inline]
Distance point line.
References gtl::Ray< Type >::getSqrDistance().
template<typename Type> const Vec3<Type>& gtl::Ray< Type >::getOrigin () const [inline]
Return the ray origin.
Referenced by gtl::Sphere< Type >::intersect(), gtl::Plane< Type >::intersect(), and gtl::Box3< Type >::intersect().
template<typename Type> Type gtl::Ray< Type >::getSqrDistance (const Vec3< Type > & pt) const [inline]
Squared distance point line.
References gtl::Ray< Type >::getValue().
Referenced by gtl::Ray< Type >::getDistance().
template<typename Type> Vec3<Type> gtl::Ray< Type >::getValue (Type t) const [inline]
Get point on ray at t.
Referenced by gtl::Ray< Type >::getSqrDistance().
template<typename Type> bool gtl::Ray< Type >::intersect (const Ray< Type > & a_ray, Type & mua, Type & mub) const [inline]
Calculate the shortest line between two lines in 3D Calculate also the values of mua and mub where Pa = P1 + mua (P2 - P1) Pb = P3 + mub (P4 - P3) Return false if no solution exists.
Two lines in 3 dimensions generally don't intersect at a point, they may be parallel (no intersections) or they may be coincident (infinite intersections) but most often only their projection onto a plane intersect.. When they don't exactly intersect at a point they can be connected by a line segment, the shortest line segment is unique and is often considered to be their intersection in 3D.
References gtl::Vec3< Type >::dot(), and EPS.
template<typename Type> bool gtl::Ray< Type >::intersect (const Vec3< Type > & vert0, const Vec3< Type > & vert1, const Vec3< Type > & vert2, Vec3< Type > & a_tuv) const [inline]
Intersect the ray with the given triangle defined by vert0,vert1,vert2. Return true if there is an intersection. If there is an intersection, a vector a_tuv is returned, where t is the distance to the plane in which the triangle lies and (u,v) represents the coordinates inside the triangle.
References gtl::Vec3< Type >::cross(), gtl::Vec3< Type >::dot(), and EPS.
template<typename Type> Vec3<Type> gtl::Ray< Type >::project (const Vec3< Type > & pt) const [inline]
Project the given point on the ray.
template<typename Type> Ray<Type> gtl::Ray< Type >::reflect (const Vec3< Type > & newOrigin, const Vec3< Type > & normal) const [inline]
Reflects about normal and return a new ray with origin at newOrigin.
template<typename Type> void gtl::Ray< Type >::setValue (const Vec3< Type > & a_origin, const Vec3< Type > & a_direction, bool normalize = true) [inline]
Set position and direction of the ray. If normalize is true, a_direction will be normalized.
Referenced by gtl::Plane< Type >::intersect(), and gtl::Ray< Type >::Ray().
Friends And Related Function Documentation
template<typename Type> bool operator!= (const Ray< Type > & r1, const Ray< Type > & r2) [friend]
Check the two given ray for inequality.
template<typename Type> bool operator== (const Ray< Type > & r1, const Ray< Type > & r2) [friend]
Check the two given ray for equality.
The documentation for this class was generated from the following file:
ray.hpp