gtl: gtl::Vec2< Type > Class Template Reference
gtl::Vec2< Type > Class Template Reference
2 dimensional vector.This class is used by many other classes.
#include <geometry/Vec2.hpp>
Public Member Functions
Vec2 ()
The default constructor.The vector will be null.
Vec2 (const Type v[2])
Constructs an instance with initial values from v.
Vec2 (Type a_x, Type a_y)
Constructs an instance with the initial values from a_x and a_y.
Vec2 (const Vec2< Type > &a_vec)
Constructs an instance with initial values from a_vec.
virtual ~Vec2 ()
Default destructor does nothing.
Vec2< Type > & setValue (const Type v[2])
Set new x and y coordinates for the vector. Returns reference to self.
Vec2< Type > & setValue (Type a_x, Type a_y)
Set new x and y coordinates for the vector. Returns reference to self.
const Type * getValue () const
Returns a pointer to an array containing the coordinates of the vector.
Type dot (const Vec2< Type > &a_vec) const
Calculates and returns the dot product of this vector with a_vec.
Type length () const
Return length of vector.
Type sqrLength () const
Return squared length of vector.
Type normalize ()
Normalize the vector to unit length. Return value is the original length of the vector before normalization.
Type cross (const Vec2< Type > &a_vec)
Returns the cross product of this vector with a_vec.
void negate ()
Negate the vector (i.e. point it in the opposite direction).
Type & x ()
Return modifiable x value.
Type & y ()
Return modifiable y value.
const Type & x () const
Return x value.
const Type & y () const
Return y value.
Type & operator[] (int i)
Index operator. Returns modifiable x or y value.
const Type & operator[] (int i) const
Index operator. Returns x or y value.
Vec2< Type > & operator*= (const Type d)
Multiply components of vector with value d. Returns reference to self.
Vec2< Type > & operator/= (const Type d)
Divides components of vector with value d. Returns reference to self.
Vec2< Type > & operator*= (const Vec2< Type > &a_vec)
Multiply components of vector with value a_vec.
Vec2< Type > & operator+= (const Vec2< Type > &a_vec)
Adds this vector and vector a_vec. Returns reference to self.
Vec2< Type > & operator-= (const Vec2< Type > &a_vec)
Subtracts vector a_vec from this vector. Returns reference to self.
Vec2< Type > operator- () const
Non-destructive negation operator.
bool equals (const Vec2< Type > &a_vec, const Type a_tolerance=1E-2) const
Check for equality with given tolerance.
Static Public Member Functions
static Vec2< Type > max ()
Largest representable vector.
Friends
Vec2< Type > operator* (const Vec2< Type > &a_vec, const Type d)
Vec2< Type > operator* (const Type d, const Vec2< Type > &a_vec)
Vec2< Type > operator/ (const Vec2< Type > &a_vec, const Type d)
Vec2< Type > operator* (const Vec2< Type > &v1, const Vec2< Type > &v2)
Vec2< Type > operator+ (const Vec2< Type > &v1, const Vec2< Type > &v2)
Vec2< Type > operator- (const Vec2< Type > &v1, const Vec2< Type > &v2)
bool operator== (const Vec2< Type > &v1, const Vec2< Type > &v2)
Check the two given vector for equality.
bool operator!= (const Vec2< Type > &v1, const Vec2< Type > &v2)
Check the two given vector for inequality.
std::ostream & operator<< (std::ostream &os, const Vec2< Type > &vect)
Detailed Description
template<typename Type>
class gtl::Vec2< Type >
2 dimensional vector.
This class is used by many other classes.
See also:
Vec3
Constructor & Destructor Documentation
template<typename Type> gtl::Vec2< Type >::Vec2 () [inline]
The default constructor.The vector will be null.
References gtl::Vec2< Type >::setValue().
template<typename Type> gtl::Vec2< Type >::Vec2 (const Type v[2]) [inline]
Constructs an instance with initial values from v.
References gtl::Vec2< Type >::setValue().
template<typename Type> gtl::Vec2< Type >::Vec2 (Type a_x, Type a_y) [inline]
Constructs an instance with the initial values from a_x and a_y.
References gtl::Vec2< Type >::setValue().
template<typename Type> gtl::Vec2< Type >::Vec2 (const Vec2< Type > & a_vec) [inline]
Constructs an instance with initial values from a_vec.
References gtl::Vec2< Type >::setValue().
template<typename Type> virtual gtl::Vec2< Type >::~Vec2 () [inline, virtual]
Default destructor does nothing.
Member Function Documentation
template<typename Type> Type gtl::Vec2< Type >::cross (const Vec2< Type > & a_vec) [inline]
Returns the cross product of this vector with a_vec.
template<typename Type> Type gtl::Vec2< Type >::dot (const Vec2< Type > & a_vec) const [inline]
Calculates and returns the dot product of this vector with a_vec.
template<typename Type> bool gtl::Vec2< Type >::equals (const Vec2< Type > & a_vec, const Type a_tolerance = 1E-2) const [inline]
Check for equality with given tolerance.
References gtl::Vec2< Type >::sqrLength().
template<typename Type> const Type* gtl::Vec2< Type >::getValue () const [inline]
Returns a pointer to an array containing the coordinates of the vector.
template<typename Type> Type gtl::Vec2< Type >::length () const [inline]
Return length of vector.
References gtl::Vec2< Type >::sqrLength().
Referenced by gtl::Circle< Type >::intersect(), and gtl::Vec2< Type >::normalize().
template<typename Type> static Vec2<Type> gtl::Vec2< Type >::max () [inline, static]
Largest representable vector.
template<typename Type> void gtl::Vec2< Type >::negate () [inline]
Negate the vector (i.e. point it in the opposite direction).
References gtl::Vec2< Type >::setValue().
template<typename Type> Type gtl::Vec2< Type >::normalize () [inline]
Normalize the vector to unit length. Return value is the original length of the vector before normalization.
References gtl::Vec2< Type >::length(), and gtl::Vec2< Type >::setValue().
template<typename Type> Vec2<Type>& gtl::Vec2< Type >::operator*= (const Vec2< Type > & a_vec) [inline]
Multiply components of vector with value a_vec.
template<typename Type> Vec2<Type>& gtl::Vec2< Type >::operator*= (const Type d) [inline]
Multiply components of vector with value d. Returns reference to self.
template<typename Type> Vec2<Type>& gtl::Vec2< Type >::operator+= (const Vec2< Type > & a_vec) [inline]
Adds this vector and vector a_vec. Returns reference to self.
template<typename Type> Vec2<Type> gtl::Vec2< Type >::operator- () const [inline]
Non-destructive negation operator.
template<typename Type> Vec2<Type>& gtl::Vec2< Type >::operator-= (const Vec2< Type > & a_vec) [inline]
Subtracts vector a_vec from this vector. Returns reference to self.
template<typename Type> Vec2<Type>& gtl::Vec2< Type >::operator/= (const Type d) [inline]
Divides components of vector with value d. Returns reference to self.
template<typename Type> const Type& gtl::Vec2< Type >::operator[] (int i) const [inline]
Index operator. Returns x or y value.
template<typename Type> Type& gtl::Vec2< Type >::operator[] (int i) [inline]
Index operator. Returns modifiable x or y value.
template<typename Type> Vec2<Type>& gtl::Vec2< Type >::setValue (Type a_x, Type a_y) [inline]
Set new x and y coordinates for the vector. Returns reference to self.
template<typename Type> Vec2<Type>& gtl::Vec2< Type >::setValue (const Type v[2]) [inline]
Set new x and y coordinates for the vector. Returns reference to self.
Referenced by gtl::Vec2< Type >::negate(), gtl::Vec2< Type >::normalize(), and gtl::Vec2< Type >::Vec2().
template<typename Type> Type gtl::Vec2< Type >::sqrLength () const [inline]
Return squared length of vector.
Referenced by gtl::Vec2< Type >::equals(), gtl::Vec2< Type >::length(), and gtl::Circle< Type >::setValue().
template<typename Type> const Type& gtl::Vec2< Type >::x () const [inline]
Return x value.
template<typename Type> Type& gtl::Vec2< Type >::x () [inline]
Return modifiable x value.
Referenced by gtl::Polygon< Type >::intersect(), and gtl::Circle< Type >::setValue().
template<typename Type> const Type& gtl::Vec2< Type >::y () const [inline]
Return y value.
template<typename Type> Type& gtl::Vec2< Type >::y () [inline]
Return modifiable y value.
Referenced by gtl::Polygon< Type >::intersect(), and gtl::Circle< Type >::setValue().
Friends And Related Function Documentation
template<typename Type> bool operator!= (const Vec2< Type > & v1, const Vec2< Type > & v2) [friend]
Check the two given vector for inequality.
template<typename Type> Vec2<Type> operator* (const Vec2< Type > & v1, const Vec2< Type > & v2) [friend]
template<typename Type> Vec2<Type> operator* (const Type d, const Vec2< Type > & a_vec) [friend]
template<typename Type> Vec2<Type> operator* (const Vec2< Type > & a_vec, const Type d) [friend]
template<typename Type> Vec2<Type> operator+ (const Vec2< Type > & v1, const Vec2< Type > & v2) [friend]
template<typename Type> Vec2<Type> operator- (const Vec2< Type > & v1, const Vec2< Type > & v2) [friend]
template<typename Type> Vec2<Type> operator/ (const Vec2< Type > & a_vec, const Type d) [friend]
template<typename Type> std::ostream& operator<< (std::ostream & os, const Vec2< Type > & vect) [friend]
template<typename Type> bool operator== (const Vec2< Type > & v1, const Vec2< Type > & v2) [friend]
Check the two given vector for equality.
The documentation for this class was generated from the following file:
vec2.hpp