gtl: gtl::Quat< Type > Class Template Reference
gtl::Quat< Type > Class Template Reference
Object that stores a rotation.All angles are in degree and all rotations are right-handed. The rotation is internally stored as a quaternion. This class is used by many other classes.
#include <geometry/Quat.hpp>
Public Member Functions
Quat ()
The default constructor just initializes a valid rotation.
Quat (const Vec3< Type > &a_axis, Type a_degree)
Construct a quaternion initialized with the given axis-of-rotation and rotation angle.
Quat (Type q0, Type q1, Type q2, Type q3)
Construct a quaternion initialized with the given quaternion components.
Quat (const Matrix4< Type > &a_matrix)
Construct a quaternion initialized with the given rotation matrix.
Quat (const Vec3< Type > &a_rotate_from, const Vec3< Type > &a_rotate_to)
Construct a quaternion which is the minimum rotation necessary to make vector rotate_from point in the direction of vector rotate_to.
virtual ~Quat ()
Default destructor does nothing.
void makeIdentity ()
Set the quaternion to be the identity.
bool isIdentity () const
Check if quaternion is identity.
Type normalize ()
Normalizes a rotation quaternion to unit 4D length. Return value is the original length of the vector before normalization.
void setValue (Type q0, Type q1, Type q2, Type q3)
Set the rotation.
void setValue (const Type q[4])
Reset the rotation by the four quaternions in the array.
void setValue (const Matrix4< Type > &a_matrix)
Set the rotation from the components of the given matrix.
void setValue (const Vec3< Type > &a_axis, Type a_degree)
Reset rotation with the given axis-of-rotation and rotation angle.
void setValue (const Vec3< Type > &a_rotate_from, const Vec3< Type > &a_rotate_to)
Construct a rotation which is the minimum rotation necessary to make vector rotate_from point in the direction of vector rotate_to.
void setValue (Type yaw, Type pitch, Type roll)
Euler-to-quaternion conversion.
const Vec4< Type > & getValue () const
Return the four quaternion components representing the rotation.
void getValue (Vec3< Type > &a_axis, Type &a_degree) const
Return the rotation in the form of an axis-of-rotation and a rotation angle.
void getValue (Type &yaw, Type &pitch, Type &roll) const
Matrix4< Type > getMatrix () const
Return this rotation in the form of a matrix.
Quat< Type > & invert ()
Invert the rotation. Returns reference to self.
Quat< Type > inverse () const
Non-destructively inverses the rotation and returns the result.
Quat< Type > & operator*= (const Quat< Type > &a_quat)
Multiplies the quaternions.
Quat< Type > & operator*= (Type a_scale)
Multiplies components of quaternion with scalar value a_scale.
bool equals (const Quat< Type > &a_quat, Type a_tolerance=1E-2) const
Check for equality with given tolerance.
void multVec (const Vec3< Type > &src, Vec3< Type > &dst) const
Rotate the src vector and put the result in dst.
void scaleAngle (Type a_scale_factor)
Scale the angle of rotation by a_scale_factor.
Static Public Member Functions
static Quat< Type > slerp (const Quat< Type > &rot0, const Quat< Type > &rot1, Type t)
Interpolates along the shortest path between the two rotation positions (from rot0 to rot1, 0<= t <= 1).
Friends
bool operator== (const Quat< Type > &q1, const Quat< Type > &q2)
Check the two given quaternion for equality.
bool operator!= (const Quat< Type > &q1, const Quat< Type > &q2)
Check the two given quaternion for inequality.
Quat< Type > operator* (const Quat< Type > &q1, const Quat< Type > &q2)
Multiplies the two quaternions and returns the result.
Vec3< Type > operator* (const Quat< Type > &q1, const Vec3< Type > &v1)
Detailed Description
template<typename Type>
class gtl::Quat< Type >
Object that stores a rotation.
All angles are in degree and all rotations are right-handed. The rotation is internally stored as a quaternion. This class is used by many other classes.
See also:
Matrix4
Constructor & Destructor Documentation
template<typename Type> gtl::Quat< Type >::Quat () [inline]
The default constructor just initializes a valid rotation.
References gtl::Quat< Type >::makeIdentity().
template<typename Type> gtl::Quat< Type >::Quat (const Vec3< Type > & a_axis, Type a_degree) [inline]
Construct a quaternion initialized with the given axis-of-rotation and rotation angle.
References gtl::Quat< Type >::setValue().
template<typename Type> gtl::Quat< Type >::Quat (Type q0, Type q1, Type q2, Type q3) [inline]
Construct a quaternion initialized with the given quaternion components.
References gtl::Quat< Type >::setValue().
template<typename Type> gtl::Quat< Type >::Quat (const Matrix4< Type > & a_matrix) [inline]
Construct a quaternion initialized with the given rotation matrix.
References gtl::Quat< Type >::setValue().
template<typename Type> gtl::Quat< Type >::Quat (const Vec3< Type > & a_rotate_from, const Vec3< Type > & a_rotate_to) [inline]
Construct a quaternion which is the minimum rotation necessary to make vector rotate_from point in the direction of vector rotate_to.
References gtl::Quat< Type >::setValue().
template<typename Type> virtual gtl::Quat< Type >::~Quat () [inline, virtual]
Default destructor does nothing.
Member Function Documentation
template<typename Type> bool gtl::Quat< Type >::equals (const Quat< Type > & a_quat, Type a_tolerance = 1E-2) const [inline]
Check for equality with given tolerance.
template<typename Type> Matrix4<Type> gtl::Quat< Type >::getMatrix () const [inline]
Return this rotation in the form of a matrix.
Referenced by gtl::Matrix4< Type >::setRotate().
template<typename Type> void gtl::Quat< Type >::getValue (Type & yaw, Type & pitch, Type & roll) const [inline]
References gtl::RadToDeg().
template<typename Type> void gtl::Quat< Type >::getValue (Vec3< Type > & a_axis, Type & a_degree) const [inline]
Return the rotation in the form of an axis-of-rotation and a rotation angle.
References gtl::DegToRad(), and gtl::Vec3< Type >::setValue().
template<typename Type> const Vec4<Type>& gtl::Quat< Type >::getValue () const [inline]
Return the four quaternion components representing the rotation.
Referenced by gtl::Quat< Type >::scaleAngle(), and gtl::Matrix3< Type >::setRotate().
template<typename Type> Quat<Type> gtl::Quat< Type >::inverse () const [inline]
Non-destructively inverses the rotation and returns the result.
References gtl::Quat< Type >::invert().
template<typename Type> Quat<Type>& gtl::Quat< Type >::invert () [inline]
Invert the rotation. Returns reference to self.
Referenced by gtl::Quat< Type >::inverse().
template<typename Type> bool gtl::Quat< Type >::isIdentity () const [inline]
Check if quaternion is identity.
template<typename Type> void gtl::Quat< Type >::makeIdentity () [inline]
Set the quaternion to be the identity.
See also:
isIdentity().
References gtl::Quat< Type >::setValue().
Referenced by gtl::Quat< Type >::Quat().
template<typename Type> void gtl::Quat< Type >::multVec (const Vec3< Type > & src, Vec3< Type > & dst) const [inline]
Rotate the src vector and put the result in dst.
References gtl::Vec3< Type >::setValue().
template<typename Type> Type gtl::Quat< Type >::normalize () [inline]
Normalizes a rotation quaternion to unit 4D length. Return value is the original length of the vector before normalization.
template<typename Type> Quat<Type>& gtl::Quat< Type >::operator*= (Type a_scale) [inline]
Multiplies components of quaternion with scalar value a_scale.
template<typename Type> Quat<Type>& gtl::Quat< Type >::operator*= (const Quat< Type > & a_quat) [inline]
Multiplies the quaternions.
References gtl::Quat< Type >::setValue().
Referenced by gtl::Quat< Type >::setValue().
template<typename Type> void gtl::Quat< Type >::scaleAngle (Type a_scale_factor) [inline]
Scale the angle of rotation by a_scale_factor.
References gtl::Quat< Type >::getValue(), and gtl::Quat< Type >::setValue().
template<typename Type> void gtl::Quat< Type >::setValue (Type yaw, Type pitch, Type roll) [inline]
Euler-to-quaternion conversion.
References gtl::DegToRad().
template<typename Type> void gtl::Quat< Type >::setValue (const Vec3< Type > & a_rotate_from, const Vec3< Type > & a_rotate_to) [inline]
Construct a rotation which is the minimum rotation necessary to make vector rotate_from point in the direction of vector rotate_to.
References gtl::Vec3< Type >::cross(), gtl::Vec3< Type >::dot(), gtl::Vec3< Type >::length(), gtl::Vec3< Type >::normalize(), and gtl::Quat< Type >::setValue().
template<typename Type> void gtl::Quat< Type >::setValue (const Vec3< Type > & a_axis, Type a_degree) [inline]
Reset rotation with the given axis-of-rotation and rotation angle.
References gtl::DegToRad(), and gtl::Vec3< Type >::normalize().
template<typename Type> void gtl::Quat< Type >::setValue (const Matrix4< Type > & a_matrix) [inline]
Set the rotation from the components of the given matrix.
References gtl::Quat< Type >::operator*=().
template<typename Type> void gtl::Quat< Type >::setValue (const Type q[4]) [inline]
Reset the rotation by the four quaternions in the array.
References gtl::Quat< Type >::setValue().
template<typename Type> void gtl::Quat< Type >::setValue (Type q0, Type q1, Type q2, Type q3) [inline]
Set the rotation.
Referenced by gtl::Quat< Type >::makeIdentity(), gtl::Quat< Type >::operator*=(), gtl::Quat< Type >::Quat(), gtl::Quat< Type >::scaleAngle(), and gtl::Quat< Type >::setValue().
template<typename Type> static Quat<Type> gtl::Quat< Type >::slerp (const Quat< Type > & rot0, const Quat< Type > & rot1, Type t) [inline, static]
Interpolates along the shortest path between the two rotation positions (from rot0 to rot1, 0<= t <= 1).
Friends And Related Function Documentation
template<typename Type> bool operator!= (const Quat< Type > & q1, const Quat< Type > & q2) [friend]
Check the two given quaternion for inequality.
template<typename Type> Vec3<Type> operator* (const Quat< Type > & q1, const Vec3< Type > & v1) [friend]
template<typename Type> Quat<Type> operator* (const Quat< Type > & q1, const Quat< Type > & q2) [friend]
Multiplies the two quaternions and returns the result.
template<typename Type> bool operator== (const Quat< Type > & q1, const Quat< Type > & q2) [friend]
Check the two given quaternion for equality.
The documentation for this class was generated from the following file:
quat.hpp