gtl: gtl::Matrix3< Type > Class Template Reference
gtl::Matrix3< Type > Class Template Reference
Row-major 3x3 matrix class.This class is used by many other classes.
#include <geometry/Matrix3.hpp>
Public Member Functions
Matrix3 ()
The default constructor. The matrix will be identity.
Matrix3 (const Type a11, const Type a12, const Type a13, const Type a21, const Type a22, const Type a23, const Type a31, const Type a32, const Type a33)
Constructs a matrix instance with the given initial elements.
Matrix3 (const Matrix3< Type > &a_matrix)
Constructs a matrix instance with the initial elements from the matrix argument.
Matrix3 (const Matrix4< Type > &a_matrix, int k)
Create from Matrix4 excluding row and column k.
virtual ~Matrix3 ()
Default destructor does nothing.
void makeIdentity ()
Set the matrix to be the identity matrix.
bool isIdentity () const
Check if matrix is identity.
Matrix3< Type > & invert ()
Inverse the current matrix.
Matrix3< Type > inverse () const
Return a new matrix which is the inverse matrix of this.
Matrix3< Type > & transpose ()
Transpose the current matrix.
Type det () const
Returns the determinant of the matrix.
bool equals (const Matrix3< Type > &a_matrix, Type a_tolerance=1E-2) const
Check if the a_matrix matrix is equal to this one, within the given tolerance value.
operator Type * ()
Return pointer to the matrix' 3x3 array.
Type * operator[] (int i)
Returns pointer to the 3 element array representing a matrix row. i should be within [0, 2].
const Type * operator[] (int i) const
Returns pointer to the 3 element array representing a matrix row. i should be within [0, 2].
Matrix3< Type > & operator= (const Matrix3< Type > &m)
Assignment operator. Copies the elements from a_matrix to the matrix.
Matrix3< Type > & operator= (const Quat< Type > &a_quat)
Matrix3< Type > & operator*= (const Matrix3< Type > &a_matrix)
Right-multiply with the a_matrix matrix.
void setRotate (const Quat< Type > &a_quat)
void setScale (const Type s)
Set matrix to be a pure scaling matrix. (no translation or rotation components).
void setScale (const Vec3< Type > &s)
Set matrix to be a pure scaling matrix. (no translation or rotation components).
Matrix3< Type > & multRight (const Matrix3< Type > &m)
Let this matrix be right-multiplied by m. Returns reference to self.
void multMatrixVec (const Vec3< Type > &src, Vec3< Type > &dst) const
Multiplies matrix by given column vector, giving vector result.
void multVecMatrix (const Vec3< Type > &src, Vec3< Type > &dst) const
Multiplies given row vector by matrix, giving vector result.
Friends
Matrix3< Type > operator* (const Matrix3< Type > &m1, const Matrix3< Type > &m2)
Multiplies matrix m1 with matrix m2 and returns the resultant matrix.
bool operator== (const Matrix3< Type > &m1, const Matrix3< Type > &m2)
bool operator!= (const Matrix3< Type > &m1, const Matrix3< Type > &m2)
std::ostream & operator<< (std::ostream &os, const Matrix3< Type > &mat)
Detailed Description
template<typename Type>
class gtl::Matrix3< Type >
Row-major 3x3 matrix class.
This class is used by many other classes.
See also:
Matrix4
Constructor & Destructor Documentation
template<typename Type> gtl::Matrix3< Type >::Matrix3 () [inline]
The default constructor. The matrix will be identity.
References gtl::Matrix3< Type >::makeIdentity().
template<typename Type> gtl::Matrix3< Type >::Matrix3 (const Type a11, const Type a12, const Type a13, const Type a21, const Type a22, const Type a23, const Type a31, const Type a32, const Type a33) [inline]
Constructs a matrix instance with the given initial elements.
template<typename Type> gtl::Matrix3< Type >::Matrix3 (const Matrix3< Type > & a_matrix) [inline]
Constructs a matrix instance with the initial elements from the matrix argument.
template<typename Type> gtl::Matrix3< Type >::Matrix3 (const Matrix4< Type > & a_matrix, int k) [inline]
Create from Matrix4 excluding row and column k.
template<typename Type> virtual gtl::Matrix3< Type >::~Matrix3 () [inline, virtual]
Default destructor does nothing.
Member Function Documentation
template<typename Type> Type gtl::Matrix3< Type >::det () const [inline]
Returns the determinant of the matrix.
template<typename Type> bool gtl::Matrix3< Type >::equals (const Matrix3< Type > & a_matrix, Type a_tolerance = 1E-2) const [inline]
Check if the a_matrix matrix is equal to this one, within the given tolerance value.
template<typename Type> Matrix3<Type> gtl::Matrix3< Type >::inverse () const [inline]
Return a new matrix which is the inverse matrix of this.
References gtl::Matrix3< Type >::invert().
template<typename Type> Matrix3<Type>& gtl::Matrix3< Type >::invert () [inline]
Inverse the current matrix.
Referenced by gtl::Matrix3< Type >::inverse().
template<typename Type> bool gtl::Matrix3< Type >::isIdentity () const [inline]
Check if matrix is identity.
Referenced by gtl::Matrix3< Type >::multRight().
template<typename Type> void gtl::Matrix3< Type >::makeIdentity () [inline]
Set the matrix to be the identity matrix.
See also:
isIdentity().
Referenced by gtl::Matrix3< Type >::Matrix3(), and gtl::Matrix3< Type >::setScale().
template<typename Type> void gtl::Matrix3< Type >::multMatrixVec (const Vec3< Type > & src, Vec3< Type > & dst) const [inline]
Multiplies matrix by given column vector, giving vector result.
References gtl::Vec3< Type >::setValue().
template<typename Type> Matrix3<Type>& gtl::Matrix3< Type >::multRight (const Matrix3< Type > & m) [inline]
Let this matrix be right-multiplied by m. Returns reference to self.
References gtl::Matrix3< Type >::isIdentity().
Referenced by gtl::Matrix3< Type >::operator*=().
template<typename Type> void gtl::Matrix3< Type >::multVecMatrix (const Vec3< Type > & src, Vec3< Type > & dst) const [inline]
Multiplies given row vector by matrix, giving vector result.
References gtl::Vec3< Type >::setValue().
template<typename Type> gtl::Matrix3< Type >::operator Type * () [inline]
Return pointer to the matrix' 3x3 array.
template<typename Type> Matrix3<Type>& gtl::Matrix3< Type >::operator*= (const Matrix3< Type > & a_matrix) [inline]
Right-multiply with the a_matrix matrix.
See also:
multRight().
References gtl::Matrix3< Type >::multRight().
template<typename Type> Matrix3<Type>& gtl::Matrix3< Type >::operator= (const Quat< Type > & a_quat) [inline]
References gtl::Matrix3< Type >::setRotate().
template<typename Type> Matrix3<Type>& gtl::Matrix3< Type >::operator= (const Matrix3< Type > & m) [inline]
Assignment operator. Copies the elements from a_matrix to the matrix.
template<typename Type> const Type* gtl::Matrix3< Type >::operator[] (int i) const [inline]
Returns pointer to the 3 element array representing a matrix row. i should be within [0, 2].
template<typename Type> Type* gtl::Matrix3< Type >::operator[] (int i) [inline]
Returns pointer to the 3 element array representing a matrix row. i should be within [0, 2].
template<typename Type> void gtl::Matrix3< Type >::setRotate (const Quat< Type > & a_quat) [inline]
References gtl::Quat< Type >::getValue().
Referenced by gtl::Matrix3< Type >::operator=().
template<typename Type> void gtl::Matrix3< Type >::setScale (const Vec3< Type > & s) [inline]
Set matrix to be a pure scaling matrix. (no translation or rotation components).
References gtl::Matrix3< Type >::makeIdentity().
template<typename Type> void gtl::Matrix3< Type >::setScale (const Type s) [inline]
Set matrix to be a pure scaling matrix. (no translation or rotation components).
template<typename Type> Matrix3<Type>& gtl::Matrix3< Type >::transpose () [inline]
Transpose the current matrix.
Friends And Related Function Documentation
template<typename Type> bool operator!= (const Matrix3< Type > & m1, const Matrix3< Type > & m2) [friend]
template<typename Type> Matrix3<Type> operator* (const Matrix3< Type > & m1, const Matrix3< Type > & m2) [friend]
Multiplies matrix m1 with matrix m2 and returns the resultant matrix.
template<typename Type> std::ostream& operator<< (std::ostream & os, const Matrix3< Type > & mat) [friend]
template<typename Type> bool operator== (const Matrix3< Type > & m1, const Matrix3< Type > & m2) [friend]
Compare matrices to see if they are equal. For two matrices to be equal, all their individual elements must be equal.
See also:
equals().
The documentation for this class was generated from the following file:
matrix3.hpp