gtl: gtl::Circle< Type > Class Template Reference
gtl::Circle< Type > Class Template Reference
2 dimensional circle.This class is used by many other classes.
#include <gtl/circle.hpp>
Public Member Functions
Circle ()
The default constructor. Does nothing.
Circle (const Vec2< Type > &a_center, Type a_radius)
Constructs an instance with initial values from a_center and a_radius.
Circle (const Circle< Type > &a_circle)
Constructs an instance with initial values from a_circle.
Circle (const Vec2< Type > &p1, const Vec2< Type > &p2)
Construct a circle from 2 Points.
Circle (const Vec2< Type > &p1, const Vec2< Type > &p2, const Vec2< Type > &p3)
Construct a circle from 3 Points. p1, p2, p3 should be co-planar.
virtual ~Circle ()
Default destructor does nothing.
void setValue (const Vec2< Type > &a_center, Type a_radius)
Change the center and radius.
bool setValue (const Vec2< Type > &p1, const Vec2< Type > &p2, const Vec2< Type > &p3)
Sets a circle from 3 Points. p1, p2, p3 should be co-planar.
void setCenter (const Vec2< Type > &a_center)
Set the center.
void setRadius (Type a_radius)
Set the radius.
const Vec2< Type > & getCenter () const
Return the center.
Type getRadius () const
Return the radius.
Type getArea () const
Area of the circle.
Type getCircumference () const
Circumference of the circle.
bool intersect (const Vec2< Type > &a_point) const
Check if a_point lies within the boundaries of this circle.
bool intersect (const Circle< Type > &c, Vec2< Type > &p1, Vec2< Type > &p2) const
Intersect with a circle, returning true if there is an intersection.
Friends
std::ostream & operator<< (std::ostream &os, const Circle< Type > &c)
Detailed Description
template<typename Type>
class gtl::Circle< Type >
2 dimensional circle.
This class is used by many other classes.
See also:
Constructor & Destructor Documentation
template<typename Type> gtl::Circle< Type >::Circle () [inline]
The default constructor. Does nothing.
template<typename Type> gtl::Circle< Type >::Circle (const Vec2< Type > & a_center, Type a_radius) [inline]
Constructs an instance with initial values from a_center and a_radius.
References gtl::Circle< Type >::setValue().
template<typename Type> gtl::Circle< Type >::Circle (const Circle< Type > & a_circle) [inline]
Constructs an instance with initial values from a_circle.
References gtl::Circle< Type >::setValue().
template<typename Type> gtl::Circle< Type >::Circle (const Vec2< Type > & p1, const Vec2< Type > & p2) [inline]
Construct a circle from 2 Points.
template<typename Type> gtl::Circle< Type >::Circle (const Vec2< Type > & p1, const Vec2< Type > & p2, const Vec2< Type > & p3) [inline]
Construct a circle from 3 Points. p1, p2, p3 should be co-planar.
References gtl::Circle< Type >::setValue().
template<typename Type> virtual gtl::Circle< Type >::~Circle () [inline, virtual]
Default destructor does nothing.
Member Function Documentation
template<typename Type> Type gtl::Circle< Type >::getArea () const [inline]
Area of the circle.
References M_PI.
template<typename Type> const Vec2<Type>& gtl::Circle< Type >::getCenter () const [inline]
Return the center.
template<typename Type> Type gtl::Circle< Type >::getCircumference () const [inline]
Circumference of the circle.
References M_PI.
template<typename Type> Type gtl::Circle< Type >::getRadius () const [inline]
Return the radius.
template<typename Type> bool gtl::Circle< Type >::intersect (const Circle< Type > & c, Vec2< Type > & p1, Vec2< Type > & p2) const [inline]
Intersect with a circle, returning true if there is an intersection.
References gtl::Vec2< Type >::length().
template<typename Type> bool gtl::Circle< Type >::intersect (const Vec2< Type > & a_point) const [inline]
Check if a_point lies within the boundaries of this circle.
template<typename Type> void gtl::Circle< Type >::setCenter (const Vec2< Type > & a_center) [inline]
Set the center.
template<typename Type> void gtl::Circle< Type >::setRadius (Type a_radius) [inline]
Set the radius.
template<typename Type> bool gtl::Circle< Type >::setValue (const Vec2< Type > & p1, const Vec2< Type > & p2, const Vec2< Type > & p3) [inline]
Sets a circle from 3 Points. p1, p2, p3 should be co-planar.
References gtl::Vec2< Type >::sqrLength(), gtl::Vec2< Type >::x(), and gtl::Vec2< Type >::y().
template<typename Type> void gtl::Circle< Type >::setValue (const Vec2< Type > & a_center, Type a_radius) [inline]
Change the center and radius.
Referenced by gtl::Circle< Type >::Circle().
Friends And Related Function Documentation
template<typename Type> std::ostream& operator<< (std::ostream & os, const Circle< Type > & c) [friend]
The documentation for this class was generated from the following file:
circle.hpp