gtl: gtl::Line< Type > Class Template Reference
gtl::Line< Type > Class Template Reference
Represents a 2D line segment as a special case of a curve that is declared from 2 2D points.
#include <gtl/Line.hpp>
Public Member Functions
Line ()
The default constructor makes a line segment with 2 points.
Line (Vec2< Type > &start_pt, Vec2< Type > &end_pt)
Constructs a line segment from the 2 provided 2D points.
int setPoints (Vec2< Type > &start_pt, Vec2< Type > &end_pt)
Reset the two points from which the line segment is declared.
Type getDistance (Vec2< Type > point)
Returns the distance from the specified point to this line.
Static Public Member Functions
static void getEquation (Vec2< Type > &pt1, Vec2< Type > &pt2, Type &m, Type &b)
Returns the equation of a line in the form y = mx + b, given two 2D points.
Protected Attributes
Vec2< Type > m_initial_points [2]
Detailed Description
template<typename Type>
class gtl::Line< Type >
Represents a 2D line segment as a special case of a curve that is declared from 2 2D points.
Constructor & Destructor Documentation
template<typename Type> gtl::Line< Type >::Line () [inline]
The default constructor makes a line segment with 2 points.
References gtl::Line< Type >::m_initial_points, gtl::Vec2< Type >::x(), and gtl::Vec2< Type >::y().
Referenced by gtl::Line< Type >::Line().
template<typename Type> gtl::Line< Type >::Line (Vec2< Type > & start_pt, Vec2< Type > & end_pt) [inline]
Constructs a line segment from the 2 provided 2D points.
References gtl::Line< Type >::Line(), and gtl::Line< Type >::setPoints().
Member Function Documentation
template<typename Type> Type gtl::Line< Type >::getDistance (Vec2< Type > point) [inline]
Returns the distance from the specified point to this line.
References gtl::Line< Type >::getEquation(), gtl::Line< Type >::m_initial_points, SQR, gtl::Vec2< Type >::x(), and gtl::Vec2< Type >::y().
template<typename Type> static void gtl::Line< Type >::getEquation (Vec2< Type > & pt1, Vec2< Type > & pt2, Type & m, Type & b) [inline, static]
Returns the equation of a line in the form y = mx + b, given two 2D points.
References gtl::Vec2< Type >::x(), and gtl::Vec2< Type >::y().
Referenced by gtl::Line< Type >::getDistance().
template<typename Type> int gtl::Line< Type >::setPoints (Vec2< Type > & start_pt, Vec2< Type > & end_pt) [inline]
Reset the two points from which the line segment is declared.
References gtl::Line< Type >::m_initial_points.
Referenced by gtl::Line< Type >::Line().
Member Data Documentation
template<typename Type> Vec2<Type> gtl::Line< Type >::m_initial_points[2] [protected]
Referenced by gtl::Line< Type >::getDistance(), gtl::Line< Type >::Line(), and gtl::Line< Type >::setPoints().
The documentation for this class was generated from the following file:
line.hpp