gtl: gtl::Sphere< Type > Class Template Reference
gtl::Sphere< Type > Class Template Reference
Represents a sphere in 3D.This class is used by many other classes.
#include <geometry/Sphere.hpp>
Public Member Functions
Sphere ()
The default constructor.
Sphere (const Sphere< Type > &a_sphere)
Constructs an instance with initial values from a_sphere.
Sphere (const Vec3< Type > &c, Type r)
Construct a sphere given center and radius.
Sphere (const Vec3< Type > &p1, const Vec3< Type > &p2)
Construct a sphere given the poles.
Sphere (const std::vector< Vec3< Type > > &points)
Compute a fast approximation of the bounding ball for the given point set.
virtual ~Sphere ()
Default destructor does nothing.
void setValue (const Vec3< Type > &c, Type r)
Change the center and radius.
void setPoles (const Vec3< Type > &p1, const Vec3< Type > &p2)
Specify pair of antipodal points.
void setCenter (const Vec3< Type > &c)
Set the center.
void setRadius (Type r)
Set the radius.
const Vec3< Type > & getCenter () const
Return the center.
Type getRadius () const
Return the radius.
Type getVolume () const
Volume of the sphere.
Type getSurface () const
Surface of the sphere.
void circumscribe (const Box3< Type > &box)
Make the sphere containing a given box.
void extendBy (const Vec3< Type > &a_point)
Extend the boundaries of the sphere by the given point.
void extendBy (const Sphere< Type > &sphere)
Extend the boundaries of the sphere by the given sphere.
bool intersect (const Vec3< Type > &p) const
Returns true if the given point p lies within the sphere.
bool intersect (const Sphere< Type > &s) const
Intersect with a sphere, returning true if there is an intersection.
bool intersect (const Ray< Type > &r, Type &t0, Type &t1) const
Intersect ray and sphere, returning true if there is an intersection.
bool intersect (const Box3< Type > &b) const
Intersect with an axis aligned box, returning true if there is an intersection.
void getUniformSurfacePoints (std::vector< Vec3< Type > > &points, unsigned int N)
Distribute N points on the sphere (uniform).
Friends
bool operator== (const Sphere< Type > &s1, const Sphere< Type > &s2)
Check the two given sphere for equality.
bool operator!= (const Sphere< Type > &s1, const Sphere< Type > &s2)
Check the two given sphere for inequality.
Detailed Description
template<typename Type>
class gtl::Sphere< Type >
Represents a sphere in 3D.
This class is used by many other classes.
See also:
Constructor & Destructor Documentation
template<typename Type> gtl::Sphere< Type >::Sphere () [inline]
The default constructor.
template<typename Type> gtl::Sphere< Type >::Sphere (const Sphere< Type > & a_sphere) [inline]
Constructs an instance with initial values from a_sphere.
References gtl::Sphere< Type >::setValue().
template<typename Type> gtl::Sphere< Type >::Sphere (const Vec3< Type > & c, Type r) [inline]
Construct a sphere given center and radius.
References gtl::Sphere< Type >::setValue().
template<typename Type> gtl::Sphere< Type >::Sphere (const Vec3< Type > & p1, const Vec3< Type > & p2) [inline]
Construct a sphere given the poles.
References gtl::Sphere< Type >::setPoles().
template<typename Type> gtl::Sphere< Type >::Sphere (const std::vector< Vec3< Type > > & points) [inline]
Compute a fast approximation of the bounding ball for the given point set.
References gtl::Sphere< Type >::extendBy(), gtl::Box3< Type >::extendBy(), gtl::Box3< Type >::getMax(), gtl::Box3< Type >::getMin(), and gtl::Sphere< Type >::setPoles().
template<typename Type> virtual gtl::Sphere< Type >::~Sphere () [inline, virtual]
Default destructor does nothing.
Member Function Documentation
template<typename Type> void gtl::Sphere< Type >::circumscribe (const Box3< Type > & box) [inline]
Make the sphere containing a given box.
References gtl::Box3< Type >::getCenter(), and gtl::Box3< Type >::getMax().
template<typename Type> void gtl::Sphere< Type >::extendBy (const Sphere< Type > & sphere) [inline]
Extend the boundaries of the sphere by the given sphere.
References gtl::Sphere< Type >::getCenter(), gtl::Sphere< Type >::getRadius(), gtl::Sphere< Type >::intersect(), gtl::Vec3< Type >::normalize(), and gtl::Sphere< Type >::setPoles().
template<typename Type> void gtl::Sphere< Type >::extendBy (const Vec3< Type > & a_point) [inline]
Extend the boundaries of the sphere by the given point.
References gtl::Sphere< Type >::intersect(), gtl::Vec3< Type >::normalize(), and gtl::Sphere< Type >::setPoles().
Referenced by gtl::Sphere< Type >::Sphere().
template<typename Type> const Vec3<Type>& gtl::Sphere< Type >::getCenter () const [inline]
Return the center.
Referenced by gtl::Sphere< Type >::extendBy(), and gtl::Sphere< Type >::intersect().
template<typename Type> Type gtl::Sphere< Type >::getRadius () const [inline]
Return the radius.
Referenced by gtl::Sphere< Type >::extendBy(), and gtl::Sphere< Type >::intersect().
template<typename Type> Type gtl::Sphere< Type >::getSurface () const [inline]
Surface of the sphere.
References M_PI.
template<typename Type> void gtl::Sphere< Type >::getUniformSurfacePoints (std::vector< Vec3< Type > > & points, unsigned int N) [inline]
Distribute N points on the sphere (uniform).
template<typename Type> Type gtl::Sphere< Type >::getVolume () const [inline]
Volume of the sphere.
References M_PI.
template<typename Type> bool gtl::Sphere< Type >::intersect (const Box3< Type > & b) const [inline]
Intersect with an axis aligned box, returning true if there is an intersection.
References gtl::Box3< Type >::getMax(), and gtl::Box3< Type >::getMin().
template<typename Type> bool gtl::Sphere< Type >::intersect (const Ray< Type > & r, Type & t0, Type & t1) const [inline]
Intersect ray and sphere, returning true if there is an intersection.
References gtl::Vec3< Type >::dot(), gtl::Ray< Type >::getDirection(), gtl::Ray< Type >::getOrigin(), and gtl::Vec3< Type >::sqrLength().
template<typename Type> bool gtl::Sphere< Type >::intersect (const Sphere< Type > & s) const [inline]
Intersect with a sphere, returning true if there is an intersection.
References gtl::Sphere< Type >::getCenter(), and gtl::Sphere< Type >::getRadius().
template<typename Type> bool gtl::Sphere< Type >::intersect (const Vec3< Type > & p) const [inline]
Returns true if the given point p lies within the sphere.
Referenced by gtl::Sphere< Type >::extendBy().
template<typename Type> void gtl::Sphere< Type >::setCenter (const Vec3< Type > & c) [inline]
Set the center.
template<typename Type> void gtl::Sphere< Type >::setPoles (const Vec3< Type > & p1, const Vec3< Type > & p2) [inline]
Specify pair of antipodal points.
Referenced by gtl::Sphere< Type >::extendBy(), and gtl::Sphere< Type >::Sphere().
template<typename Type> void gtl::Sphere< Type >::setRadius (Type r) [inline]
Set the radius.
template<typename Type> void gtl::Sphere< Type >::setValue (const Vec3< Type > & c, Type r) [inline]
Change the center and radius.
Referenced by gtl::Sphere< Type >::Sphere().
Friends And Related Function Documentation
template<typename Type> bool operator!= (const Sphere< Type > & s1, const Sphere< Type > & s2) [friend]
Check the two given sphere for inequality.
template<typename Type> bool operator== (const Sphere< Type > & s1, const Sphere< Type > & s2) [friend]
Check the two given sphere for equality.
The documentation for this class was generated from the following file:
sphere.hpp